import type { MapDef } from '../shared/types';

/**
 * "Test map" - a short (~1.5 km) classic forest gravel stage for physics work.
 *
 * Layout (sketch with +Z drawn as "north"; procedural, so orientation doesn't matter):
 *   start (south-west) -> fast sweepers -> S-bends -> hairpin (east)
 *   -> crest jump -> long right-hander -> finish (north-east)
 * A flat gravel test pad sits next to the start (spawn with ?spawn=pad).
 */
export const testMap: MapDef = {
  id: 'test',
  name: 'Test Map',
  year: 2026,
  /** Recommended tyre (pre-selected on the car screen; see ../../PHYSICS.md). */
  tyre: 'gravel',
  description:
    'Short forest gravel stage with a hairpin, a crest jump and a flat test pad.',
  seed: 1337,
  bounds: { minX: -420, maxX: 360, minZ: -460, maxZ: 420 },
  terrain: {
    baseHeight: 0,
    layers: [
      { scale: 420, amplitude: 20, octaves: 3 },
      { scale: 140, amplitude: 5, octaves: 3, ridged: true },
      { scale: 35, amplitude: 1.2, octaves: 2 },
    ],
    edgeRise: 18,
    flatAreas: [
      {
        name: 'pad',
        x: -320,
        z: -390,
        radius: 42,
        blend: 25,
        surface: 'gravel',
      },
    ],
  },
  road: {
    width: 7,
    shoulder: 1.6,
    ditch: 0.35,
    crown: 0.06,
    smoothing: 90,
    maxGrade: 0.11,
    surface: 'gravel',
    points: [
      [-262, -400],
      [-262, -340],
      [-262, -280],
      [-250, -205],
      [-215, -145],
      [-150, -105],
      [-80, -100],
      [-30, -122],
      [20, -152],
      [68, -158],
      [100, -136],
      [112, -105],
      [100, -76],
      [68, -62],
      [28, -58],
      [-12, -38],
      { x: -26, z: -8, dy: 0 },
      { x: -32, z: 6, dy: 1.7 },
      { x: -36, z: 22, dy: 0 },
      [-34, 80],
      [6, 132],
      [70, 152],
      [140, 140],
      [200, 168],
      [232, 228],
      [212, 292],
      [160, 322],
      [100, 334],
      [40, 342],
      [-10, 344],
      // Run-off after the finish: the car auto-brakes to a stop here.
      [-70, 340],
      [-130, 328],
      [-185, 312],
    ],
  },
  stage: { start: 40, finishFromEnd: 175, splits: 2 },
  scatter: [
    {
      asset: 'pine_tree',
      density: 11,
      minRoadDist: 4.5,
      maxSlope: 0.45,
      mask: { scale: 170, threshold: -0.25 },
      scale: [0.8, 1.35],
      tilt: 3,
      sink: 0.3,
    },
    {
      asset: 'birch_tree',
      density: 3,
      minRoadDist: 3.5,
      maxSlope: 0.35,
      mask: { scale: 170, threshold: 0.1, invert: true },
      scale: [0.8, 1.2],
      tilt: 4,
      sink: 0.2,
    },
    {
      asset: 'bush',
      density: 7,
      minRoadDist: 2.2,
      maxSlope: 0.5,
      scale: [0.7, 1.4],
      sink: 0.15,
    },
    {
      asset: 'rock_boulder',
      density: 0.9,
      minRoadDist: 3.5,
      scale: [0.6, 1.8],
      alignToGround: true,
      sink: 0.35,
    },
    {
      asset: 'rock_small',
      density: 4,
      minRoadDist: 1.6,
      scale: [0.6, 1.5],
      alignToGround: true,
      sink: 0.08,
    },
    {
      asset: 'grass_tuft',
      density: 320,
      detail: true,
      minRoadDist: 1.4,
      maxSlope: 0.35,
      scale: [0.7, 1.4],
    },
  ],
  roadside: [
    {
      asset: 'marker_post',
      every: 50,
      side: 'both',
      offset: 1.4,
      faceRoad: true,
    },
    {
      asset: 'chevron_sign',
      every: 9,
      maxRadius: 38,
      side: 'outside',
      offset: 3.2,
      faceRoad: true,
    },
    {
      asset: 'hay_bale',
      every: 14,
      maxRadius: 30,
      side: 'outside',
      offset: 2.2,
      count: 2,
      spread: 3,
    },
    // Crowds at the hairpin and the jump.
    {
      asset: 'spectator',
      at: [628, 662, 845],
      side: 'outside',
      offset: 9,
      count: 9,
      spread: 14,
      depth: 3,
      faceRoad: true,
    },
    {
      asset: 'tape_post',
      at: [628, 662, 845],
      side: 'outside',
      offset: 6,
      count: 6,
      spread: 16,
    },
  ],
  // Start / finish gantries, lines and split boards come from `stage` (world/stage-signs.ts).
  props: [],
  environment: {
    sunElevation: 32,
    sunAzimuth: 215,
    turbidity: 4,
    rayleigh: 1.2,
    fogColor: '#a3b3c4',
    fogDensity: 0.0013,
    exposure: 0.8,
  },
};
