import type { ItemDef } from './catalog';
import type { MoveKind } from '../map/types';

/**
 * Construction Site edible catalog (the fourth map). Data only: size, tier, level and points are derived from
 * the dimensions in catalog.ts like every other item. `homes` = the districts the generator may place it in
 * (CONSTRUCTION-SITE.md section 3), `motion` = how it moves ('-' = static). Builders: build-site.ts (materials,
 * tools, crew, site furniture, heaps) and build-machines.ts (plant, trucks, cranes, mining, structures).
 * Vehicles and machines run along X, workers and signs face +Z.
 */
export type District =
  | 'gate'
  | 'brickyard'
  | 'roadworks'
  | 'housing'
  | 'yard'
  | 'foundations'
  | 'depot'
  | 'towers'
  | 'mine';

export const DISTRICTS: District[] = [
  'gate',
  'brickyard',
  'roadworks',
  'housing',
  'yard',
  'foundations',
  'depot',
  'towers',
  'mine',
];

/** Where an item may stand: listed districts, or every district. */
export type Homes = District[] | 'everywhere';
export type SiteMotion = MoveKind | '-';

export type ConstructionDef = ItemDef & {
  homes: Homes;
  motion: SiteMotion;
};

const HIVIS = [0xf08a2b, 0xf2c230, 0xb5e03a];
const HAT = [0xf2c230, 0xf4f1ea, 0xf08a2b, 0x3b82d6];
const BUCKET = [0xf4f1ea, 0x3b82d6, 0xd94a3a];
const TOOLBOX = [0xd94a3a, 0x3b82d6, 0xf2c230];
const CAN = [0xd94a3a, 0x4fa84a, 0xf2c230];
const DRUM = [0x3b82d6, 0xd94a3a, 0xf2c230, 0x4fa84a];
const BRICK = [0xb4573c, 0xc46a3e, 0x9c4a35, 0xd9a066];
const MACHINE = [0xf2c230, 0xf08a2b];
const TRUCK = [0xf4f1ea, 0xd94a3a, 0x3b82d6, 0xf2c230, 0x4fa84a];
const CONTAINER = [0xd94a3a, 0x3b82d6, 0x4fa84a, 0xf08a2b, 0x8b9298];
const LOO = [0x3b82d6, 0x4fa84a, 0xf08a2b];
const TARP = [0x3b82d6, 0x4fa84a, 0xf08a2b];
const CABIN = [0xf4f1ea, 0xf2c230, 0x3b82d6];
const CRANE = [0xf2c230, 0xd94a3a, 0xf4f1ea];
const BARRIER = [0xd94a3a, 0xf4f1ea, 0xf08a2b];
const STRIPE = [0xd94a3a, 0xf08a2b, 0x2a4f8f];

/** Window material of the buildings under construction; everything else is plain vertex colour. */
const STYLE: Record<string, ItemDef['style']> = {
  apartment_shell: 'punched',
  highrise_shell: 'glass',
  highrise_tall: 'ribbon',
  tower_topping: 'glass',
};

type Opts = Partial<Pick<ItemDef, 'variants' | 'paints'>>;

function def(
  id: string,
  name: string,
  group: ItemDef['group'],
  w: number,
  d: number,
  h: number,
  where: string,
  homes: Homes,
  motion: SiteMotion = '-',
  o: Opts = {},
): ConstructionDef {
  return {
    id,
    name,
    group,
    w,
    d,
    h,
    where,
    variants: o.variants ?? 1,
    style: STYLE[id] ?? 'prop',
    paints: o.paints,
    map: 'construction',
    homes,
    motion,
  };
}

const HEAP = { variants: 3 };

export const CONSTRUCTION_DEFS: ConstructionDef[] = [
  // tier 1 (level 1)
  def(
    'brick',
    'Brick',
    'material',
    0.24,
    0.12,
    0.08,
    'everywhere, spilled from pallets',
    'everywhere',
    '-',
    { paints: BRICK },
  ),
  def(
    'hard_hat',
    'Hard hat',
    'tools',
    0.3,
    0.24,
    0.16,
    'dropped by the crews',
    'everywhere',
    '-',
    { paints: HAT },
  ),
  def(
    'paint_bucket',
    'Paint bucket',
    'tools',
    0.3,
    0.3,
    0.36,
    'housing, gate',
    ['housing', 'gate', 'towers'],
    '-',
    { paints: BUCKET },
  ),
  def(
    'jerrycan',
    'Jerrycan',
    'tools',
    0.36,
    0.18,
    0.46,
    'next to the plant',
    ['depot', 'roadworks', 'mine', 'yard'],
    '-',
    { paints: CAN },
  ),
  def(
    'concrete_block',
    'Concrete block',
    'material',
    0.4,
    0.2,
    0.2,
    'everywhere',
    'everywhere',
  ),
  def(
    'road_cone',
    'Road cone',
    'site',
    0.4,
    0.4,
    0.72,
    'along the haul roads',
    'everywhere',
  ),
  def(
    'toolbox',
    'Toolbox',
    'tools',
    0.5,
    0.24,
    0.26,
    'with the crews',
    'everywhere',
    '-',
    { paints: TOOLBOX },
  ),
  def(
    'worker',
    'Worker',
    'crew',
    0.5,
    0.32,
    1.76,
    'walks around its work spot, runs from the hole',
    'everywhere',
    'wander',
    { paints: HIVIS },
  ),
  def(
    'cement_bag',
    'Cement bag',
    'material',
    0.6,
    0.4,
    0.14,
    'brickyard, foundations',
    'everywhere',
  ),
  def(
    'oil_drum',
    'Oil drum',
    'material',
    0.6,
    0.6,
    0.88,
    'depot, mine, yard',
    ['depot', 'mine', 'yard', 'roadworks'],
    '-',
    { paints: DRUM },
  ),
  def(
    'hazard_sign',
    'Warning sign',
    'site',
    0.62,
    0.4,
    1.1,
    'on a stand by the work',
    'everywhere',
  ),
  def(
    'sandbag',
    'Sandbag',
    'material',
    0.62,
    0.36,
    0.16,
    'roadworks, foundations',
    ['roadworks', 'foundations', 'gate', 'mine'],
  ),
  def(
    'temp_light',
    'Temporary traffic light',
    'site',
    0.6,
    0.6,
    3.2,
    'roadworks',
    ['roadworks', 'gate'],
  ),
  def(
    'heap_xs',
    'Tiny heap',
    'heaps',
    0.85,
    0.85,
    0.3,
    'dirt, sand, gravel',
    'everywhere',
    '-',
    HEAP,
  ),
  def(
    'sledgehammer',
    'Sledgehammer',
    'tools',
    0.86,
    0.22,
    0.1,
    'foundations, housing',
    ['foundations', 'housing', 'brickyard', 'gate'],
  ),
  // tier 2 (level 2)
  def(
    'plate_compactor',
    'Plate compactor',
    'tools',
    0.96,
    0.52,
    1.0,
    'roadworks, foundations',
    ['roadworks', 'foundations', 'housing'],
  ),
  def(
    'kerb_stack',
    'Kerb stones',
    'material',
    0.98,
    0.62,
    0.5,
    'roadworks, brickyard',
    ['roadworks', 'brickyard'],
  ),
  def('shovel', 'Shovel', 'tools', 1.0, 0.24, 0.1, 'everywhere', 'everywhere'),
  def(
    'rebar_bundle',
    'Rebar bundle',
    'material',
    1.02,
    0.3,
    0.16,
    'foundations, towers',
    ['foundations', 'towers', 'yard'],
  ),
  def(
    'barricade',
    'Barricade',
    'site',
    1.04,
    0.5,
    1.0,
    'roadworks, gate',
    ['roadworks', 'gate', 'foundations'],
    '-',
    { paints: STRIPE },
  ),
  // tier 3
  def(
    'brick_pallet',
    'Pallet of bricks',
    'material',
    1.18,
    1.0,
    0.96,
    'brickyard, housing',
    ['brickyard', 'housing', 'gate'],
    '-',
    { paints: BRICK },
  ),
  def(
    'generator',
    'Generator',
    'tools',
    1.16,
    0.7,
    0.78,
    'everywhere',
    'everywhere',
    '-',
    { paints: MACHINE },
  ),
  def(
    'cement_mixer',
    'Cement mixer',
    'tools',
    1.2,
    0.8,
    1.3,
    'brickyard, housing',
    ['brickyard', 'housing', 'foundations'],
    '-',
    { paints: TOOLBOX },
  ),
  def(
    'water_barrier',
    'Water-filled barrier',
    'site',
    1.2,
    0.48,
    0.82,
    'roadworks',
    ['roadworks', 'gate', 'depot'],
    '-',
    { paints: BARRIER },
  ),
  def(
    'ibc_tank',
    'Water tank',
    'material',
    1.2,
    1.0,
    1.16,
    'yard, foundations',
    ['yard', 'foundations', 'brickyard'],
  ),
  def(
    'portaloo',
    'Portable toilet',
    'site',
    1.2,
    1.2,
    2.3,
    'gate, every work area',
    'everywhere',
    '-',
    { paints: LOO },
  ),
  // tier 4
  def(
    'block_pallet',
    'Pallet of blocks',
    'material',
    1.3,
    1.1,
    1.0,
    'brickyard, housing',
    ['brickyard', 'housing'],
  ),
  def('gas_cage', 'Gas bottle cage', 'tools', 1.3, 0.8, 1.6, 'yard, gate', [
    'yard',
    'gate',
    'towers',
  ]),
  def(
    'tarp_pallet',
    'Covered pallet',
    'material',
    1.36,
    1.1,
    1.1,
    'yard, brickyard',
    ['yard', 'brickyard', 'housing'],
    '-',
    { paints: TARP },
  ),
  def(
    'wheelbarrow',
    'Wheelbarrow',
    'tools',
    1.4,
    0.64,
    0.66,
    'everywhere',
    'everywhere',
    '-',
    { paints: [0x4fa84a, 0xf08a2b, 0xf2c230] },
  ),
  // tier 5 (level 3)
  def(
    'manhole_rings',
    'Manhole rings',
    'material',
    1.5,
    1.5,
    1.3,
    'roadworks, yard',
    ['roadworks', 'yard'],
  ),
  def(
    'scaffold_tower',
    'Scaffold tower',
    'site',
    1.55,
    1.55,
    4.2,
    'housing, towers',
    ['housing', 'towers', 'foundations'],
  ),
  def('cable_drum', 'Cable drum', 'material', 1.6, 1.0, 1.6, 'yard, towers', [
    'yard',
    'towers',
    'roadworks',
  ]),
  def(
    'mini_dumper',
    'Mini dumper',
    'plant',
    1.6,
    0.9,
    1.3,
    'brickyard, housing',
    ['brickyard', 'housing', 'gate'],
    '-',
    { paints: MACHINE },
  ),
  // tier 6
  def(
    'excavator_bucket',
    'Excavator bucket',
    'material',
    1.8,
    1.2,
    1.1,
    'depot, mine',
    ['depot', 'mine', 'foundations'],
  ),
  def(
    'walk_roller',
    'Walk-behind roller',
    'plant',
    1.85,
    0.85,
    1.15,
    'roadworks',
    ['roadworks', 'housing'],
    '-',
    { paints: MACHINE },
  ),
  def(
    'light_tower',
    'Light tower',
    'site',
    1.9,
    1.3,
    6.2,
    'everywhere',
    'everywhere',
    '-',
    { paints: MACHINE },
  ),
  def(
    'lumber_bundle',
    'Timber bundle',
    'material',
    1.9,
    1.0,
    0.8,
    'housing, yard',
    ['housing', 'yard'],
  ),
  def(
    'formwork_stack',
    'Formwork panels',
    'material',
    1.9,
    1.1,
    1.0,
    'foundations, towers',
    ['foundations', 'towers'],
  ),
  // tier 7
  def(
    'heap_s',
    'Small heap',
    'heaps',
    2.1,
    2.1,
    0.8,
    'dirt, sand, gravel',
    'everywhere',
    '-',
    HEAP,
  ),
  def(
    'compressor',
    'Air compressor',
    'tools',
    2.1,
    1.3,
    1.3,
    'roadworks, foundations',
    ['roadworks', 'foundations', 'mine'],
    '-',
    { paints: MACHINE },
  ),
  def(
    'jersey_barrier',
    'Concrete barrier',
    'site',
    2.2,
    0.6,
    0.82,
    'roadworks, mine',
    ['roadworks', 'mine', 'depot'],
  ),
  def('rebar_cage', 'Rebar cage', 'material', 2.2, 0.8, 0.8, 'foundations', [
    'foundations',
    'towers',
  ]),
  // tier 8
  def(
    'concrete_pipes',
    'Concrete pipes',
    'material',
    2.5,
    2.2,
    1.2,
    'roadworks, yard',
    ['roadworks', 'yard'],
  ),
  def(
    'scissor_lift',
    'Scissor lift',
    'plant',
    2.5,
    1.2,
    2.3,
    'towers, housing',
    ['towers', 'housing', 'yard'],
    '-',
    { paints: MACHINE },
  ),
  def(
    'mini_excavator',
    'Mini excavator',
    'plant',
    2.6,
    1.2,
    2.4,
    'housing, foundations',
    ['housing', 'foundations', 'brickyard', 'depot'],
    '-',
    { paints: MACHINE },
  ),
  def(
    'skid_steer',
    'Skid steer',
    'plant',
    2.6,
    1.6,
    2.0,
    'everywhere',
    ['brickyard', 'housing', 'yard', 'depot', 'roadworks'],
    '-',
    { paints: MACHINE },
  ),
  def(
    'pipe_stack',
    'Pipe stack',
    'material',
    2.6,
    1.6,
    1.0,
    'yard, roadworks',
    ['yard', 'roadworks'],
  ),
  // tier 9 (level 4)
  def(
    'site_forklift',
    'Forklift',
    'plant',
    3.0,
    1.3,
    2.2,
    'yard, brickyard',
    ['yard', 'brickyard'],
    'patrol',
    { paints: MACHINE },
  ),
  def('road_plate', 'Road plate', 'material', 3.0, 1.6, 0.08, 'roadworks', [
    'roadworks',
    'foundations',
  ]),
  def(
    'container_10',
    'Small container',
    'site',
    3.0,
    2.44,
    2.6,
    'yard, gate',
    ['yard', 'gate', 'depot'],
    '-',
    { paints: CONTAINER },
  ),
  def(
    'compact_roller',
    'Compact roller',
    'plant',
    3.0,
    1.4,
    2.4,
    'roadworks',
    ['roadworks', 'housing'],
    '-',
    { paints: MACHINE },
  ),
  // tier 10
  def(
    'sign_board',
    'Site sign board',
    'site',
    3.3,
    0.6,
    2.8,
    'gate, every district',
    'everywhere',
  ),
  def(
    'skip_bin',
    'Skip',
    'site',
    3.4,
    1.8,
    1.4,
    'housing, brickyard',
    ['housing', 'brickyard', 'gate', 'foundations'],
    '-',
    { paints: CONTAINER },
  ),
  def(
    'site_dumper',
    'Site dumper',
    'plant',
    3.5,
    1.9,
    2.7,
    'brickyard, foundations',
    ['brickyard', 'foundations', 'housing'],
    '-',
    { paints: MACHINE },
  ),
  def(
    'fence_panel',
    'Fence panel',
    'site',
    3.5,
    0.7,
    2.0,
    'around the work',
    'everywhere',
  ),
  // tier 11 (level 5)
  def(
    'heap_m',
    'Heap',
    'heaps',
    3.9,
    3.9,
    1.5,
    'dirt, sand, gravel',
    'everywhere',
    '-',
    HEAP,
  ),
  def('mining_tyre', 'Giant tyre', 'mining', 4.0, 1.6, 4.0, 'mine', [
    'mine',
    'depot',
  ]),
  def(
    'water_bowser',
    'Water bowser',
    'site',
    4.0,
    1.8,
    2.2,
    'gate, roadworks',
    ['gate', 'roadworks', 'depot'],
  ),
  def('steel_beams', 'Steel beams', 'material', 4.1, 1.4, 0.9, 'yard, towers', [
    'yard',
    'towers',
  ]),
  // tier 12
  def('trench_box', 'Trench box', 'material', 4.4, 2.4, 2.4, 'foundations', [
    'foundations',
    'roadworks',
  ]),
  def('fuel_tank', 'Fuel tank', 'site', 4.4, 2.0, 2.2, 'depot, mine', [
    'depot',
    'mine',
  ]),
  def(
    'cement_silo',
    'Cement silo',
    'structures',
    3.6,
    3.6,
    18,
    'towers, foundations',
    ['towers', 'foundations'],
  ),
  def(
    'tandem_roller',
    'Tandem roller',
    'plant',
    4.6,
    1.8,
    3.0,
    'roadworks',
    ['roadworks', 'depot'],
    '-',
    { paints: MACHINE },
  ),
  // tier 13 (level 6)
  def(
    'site_van',
    'Site van',
    'trucks',
    5.0,
    2.0,
    2.3,
    'drives the haul roads',
    ['gate', 'housing', 'yard'],
    'drive',
    { paints: TRUCK },
  ),
  def(
    'lumber_stack',
    'Timber stack',
    'material',
    5.2,
    1.4,
    1.4,
    'housing, yard',
    ['housing', 'yard'],
  ),
  def(
    'site_pickup',
    'Pickup truck',
    'trucks',
    5.3,
    2.0,
    1.9,
    'drives the haul roads',
    ['gate', 'roadworks', 'mine'],
    'drive',
    { paints: TRUCK },
  ),
  def(
    'telehandler',
    'Telehandler',
    'plant',
    5.4,
    2.3,
    2.5,
    'housing, yard',
    ['housing', 'yard', 'towers'],
    '-',
    { paints: MACHINE },
  ),
  // tier 14
  def(
    'site_cabin',
    'Site cabin',
    'site',
    6.0,
    2.5,
    2.7,
    'gate, every district',
    'everywhere',
    '-',
    { paints: CABIN },
  ),
  def(
    'container_20',
    'Shipping container',
    'site',
    6.06,
    2.44,
    2.6,
    'yard',
    ['yard', 'gate', 'depot'],
    '-',
    { paints: CONTAINER },
  ),
  def(
    'bulldozer',
    'Bulldozer',
    'plant',
    6.2,
    3.4,
    3.4,
    'depot, mine',
    ['depot', 'mine', 'roadworks'],
    '-',
    { paints: MACHINE },
  ),
  def(
    'backhoe',
    'Backhoe loader',
    'plant',
    6.4,
    2.3,
    3.8,
    'housing, roadworks',
    ['housing', 'roadworks', 'depot'],
    '-',
    { paints: MACHINE },
  ),
  def(
    'asphalt_paver',
    'Asphalt paver',
    'plant',
    6.4,
    3.1,
    3.6,
    'roadworks',
    ['roadworks', 'depot'],
    '-',
    { paints: MACHINE },
  ),
  // tier 15 (level 7)
  def('office_cabins', 'Office cabins', 'site', 7.0, 3.0, 5.8, 'gate', [
    'gate',
    'towers',
    'mine',
  ]),
  def(
    'foundation_slab',
    'Foundation slab',
    'structures',
    7.4,
    7.4,
    0.9,
    'housing, foundations',
    ['housing', 'foundations'],
  ),
  def(
    'heap_l',
    'Big heap',
    'heaps',
    7.4,
    7.4,
    2.8,
    'dirt, sand, gravel',
    'everywhere',
    '-',
    HEAP,
  ),
  def(
    'wheel_loader',
    'Wheel loader',
    'plant',
    7.6,
    2.8,
    3.5,
    'depot, mine',
    ['depot', 'mine', 'yard'],
    '-',
    { paints: MACHINE },
  ),
  // tier 16
  def(
    'piling_rig',
    'Piling rig',
    'plant',
    8.0,
    4.2,
    30,
    'foundations',
    ['foundations', 'towers'],
    '-',
    { paints: MACHINE },
  ),
  def(
    'dump_truck',
    'Dump truck',
    'trucks',
    8.6,
    2.6,
    3.4,
    'drives the haul roads',
    ['depot', 'mine', 'foundations'],
    'drive',
    { paints: TRUCK },
  ),
  def('house_frame', 'House frame', 'structures', 8.8, 7.4, 6.5, 'housing', [
    'housing',
  ]),
  def(
    'motor_grader',
    'Motor grader',
    'plant',
    8.9,
    2.5,
    3.4,
    'roadworks, depot',
    ['roadworks', 'depot'],
    '-',
    { paints: MACHINE },
  ),
  // tier 17 (level 8)
  def('drill_rig', 'Drill rig', 'mining', 9.4, 3.0, 9.0, 'mine', ['mine']),
  def(
    'mixer_truck',
    'Concrete mixer truck',
    'trucks',
    9.6,
    2.6,
    3.5,
    'drives the haul roads',
    ['foundations', 'towers', 'housing'],
    'drive',
    { paints: TRUCK },
  ),
  def(
    'excavator',
    'Excavator',
    'plant',
    9.8,
    3.2,
    4.6,
    'depot, foundations',
    ['depot', 'foundations', 'mine', 'housing'],
    '-',
    { paints: MACHINE },
  ),
  def('house_shell', 'House shell', 'structures', 10.0, 8.0, 7.0, 'housing', [
    'housing',
  ]),
  // tier 18
  def(
    'articulated_hauler',
    'Articulated hauler',
    'trucks',
    11.0,
    3.4,
    3.8,
    'depot, mine',
    ['depot', 'mine'],
    '-',
    { paints: MACHINE },
  ),
  def(
    'heap_xl',
    'Spoil heap',
    'heaps',
    11.5,
    11.5,
    4.0,
    'dirt, sand, gravel',
    ['mine', 'foundations', 'roadworks', 'depot', 'housing'],
    '-',
    HEAP,
  ),
  def(
    'big_excavator',
    'Big excavator',
    'plant',
    12.0,
    3.8,
    5.6,
    'depot, mine',
    ['depot', 'mine'],
    '-',
    { paints: MACHINE },
  ),
  def(
    'foundation_pit',
    'Foundation pit',
    'structures',
    12.0,
    9.0,
    1.2,
    'foundations',
    ['foundations', 'towers'],
  ),
  def(
    'pump_truck',
    'Concrete pump truck',
    'trucks',
    12.0,
    2.6,
    4.0,
    'foundations, towers',
    ['foundations', 'towers'],
    '-',
    { paints: TRUCK },
  ),
  // tier 19 (level 9)
  def('mining_dozer', 'Mining dozer', 'mining', 12.8, 6.0, 4.8, 'mine', [
    'mine',
  ]),
  def(
    'truck_crane',
    'Truck crane',
    'cranes',
    13.5,
    2.8,
    4.0,
    'towers, yard, depot',
    ['towers', 'yard', 'depot'],
    '-',
    { paints: CRANE },
  ),
  def(
    'self_erecting_crane',
    'Self-erecting crane',
    'cranes',
    14.0,
    4.0,
    22,
    'housing',
    ['housing', 'brickyard'],
    '-',
    { paints: CRANE },
  ),
  def(
    'apartment_frame',
    'Apartment frame',
    'structures',
    14.0,
    12.0,
    14.0,
    'towers, housing',
    ['towers', 'housing'],
  ),
  // tier 20 (level 10)
  def(
    'haul_truck',
    'Haul truck',
    'mining',
    15.6,
    9.8,
    7.6,
    'shuttles between the shovel and the crusher',
    ['mine'],
    'patrol',
    { paints: [0xf2c230, 0xf4f1ea] },
  ),
  def('rock_crusher', 'Rock crusher', 'mining', 16.0, 6.0, 9.0, 'mine', [
    'mine',
  ]),
  def(
    'apartment_shell',
    'Apartment shell',
    'structures',
    16.0,
    12.0,
    20,
    'towers',
    ['towers'],
  ),
  def('lowboy', 'Low loader', 'trucks', 16.4, 3.0, 4.5, 'depot', [
    'depot',
    'mine',
  ]),
  // tier 21 (level 11)
  def(
    'mobile_crane',
    'Mobile crane',
    'cranes',
    18.0,
    3.0,
    30,
    'towers, depot',
    ['towers', 'depot'],
    '-',
    { paints: CRANE },
  ),
  def(
    'batching_plant',
    'Concrete plant',
    'structures',
    18.0,
    10.0,
    20,
    'towers',
    ['towers', 'foundations'],
  ),
  def('office_frame', 'Office frame', 'structures', 18.0, 18.0, 24, 'towers', [
    'towers',
  ]),
  // tier 22 (level 12)
  def(
    'highrise_shell',
    'High-rise shell',
    'structures',
    20.0,
    20.0,
    44,
    'towers',
    ['towers'],
  ),
  def('mining_shovel', 'Mining shovel', 'mining', 21.0, 10.0, 16, 'mine', [
    'mine',
  ]),
  def(
    'tower_crane_s',
    'Small tower crane',
    'cranes',
    21.0,
    4.0,
    38,
    'towers, housing',
    ['towers', 'housing'],
    '-',
    { paints: CRANE },
  ),
  def('conveyor', 'Conveyor', 'mining', 22.0, 3.0, 9.0, 'mine', ['mine']),
  // tier 23 (level 13)
  def(
    'highrise_tall',
    'Tall high-rise',
    'structures',
    24.0,
    24.0,
    60,
    'towers',
    ['towers'],
  ),
  def(
    'titan_truck',
    'Titan haul truck',
    'mining',
    25.0,
    15.0,
    12,
    'the mine boss, a prototype twice the size of a haul truck',
    ['mine'],
    'patrol',
  ),
  def(
    'crawler_crane',
    'Crawler crane',
    'cranes',
    26.0,
    8.0,
    40,
    'towers, foundations',
    ['towers', 'foundations'],
    '-',
    { paints: CRANE },
  ),
  def(
    'tower_crane',
    'Tower crane',
    'cranes',
    26.0,
    5.0,
    48,
    'towers',
    ['towers'],
    '-',
    { paints: CRANE },
  ),
  // tier 24 (level 14)
  def(
    'heap_xxl',
    'Spoil hill',
    'heaps',
    28.0,
    28.0,
    9.0,
    'mine',
    ['mine'],
    '-',
    HEAP,
  ),
  def(
    'skyscraper_core',
    'Skyscraper core',
    'structures',
    28.0,
    28.0,
    80,
    'towers',
    ['towers'],
  ),
  def('dragline', 'Dragline', 'mining', 30.0, 14.0, 20, 'mine', ['mine']),
  def(
    'tower_crane_l',
    'Big tower crane',
    'cranes',
    30.0,
    6.0,
    56,
    'towers',
    ['towers'],
    '-',
    { paints: CRANE },
  ),
  // tier 25 (level 15)
  def(
    'tower_topping',
    'Tower topping out',
    'structures',
    32.0,
    32.0,
    96,
    'towers',
    ['towers'],
  ),
  def(
    'giant_tower_crane',
    'Giant tower crane',
    'cranes',
    34.0,
    6.0,
    64,
    'towers',
    ['towers'],
    '-',
    { paints: CRANE },
  ),
  def(
    'spoil_mountain',
    'Spoil mountain',
    'heaps',
    34.0,
    34.0,
    11,
    'mine',
    ['mine'],
    '-',
    HEAP,
  ),
  def(
    'bucket_wheel',
    'Bucket-wheel excavator',
    'mining',
    35.0,
    14.0,
    22,
    'mine',
    ['mine'],
  ),
];
