import type { ItemDef, ItemGroup } from './catalog';

/**
 * Toy Emporium edible catalog (the second map). Data only: size, tier, level and
 * points are derived from the dimensions in catalog.ts like every other item.
 * Priority P0 = first playable set, P1 = full v1, P2 = polish (see TOY-STORE.md).
 * Builders: build-plush.ts, build-toys.ts, build-toyveh.ts, build-landmarks.ts.
 */
const PRIMARY = [0xd94a3a, 0x3b82d6, 0xf2c230, 0x4fa84a, 0xf08a2b, 0x8b5cd6];
const VEHICLE = [0xd94a3a, 0x3b82d6, 0xf2f2f2, 0x4fa84a, 0xf2c230, 0xe86aa6];
const PASTEL = [0xff9ec4, 0x9ed8ff, 0xfff09e, 0xb8f0b0, 0xd2b4ff];

export type ToyPriority = 'P0' | 'P1' | 'P2';

type Opts = Partial<Pick<ItemDef, 'variants' | 'paints'>>;

function def(
  id: string,
  name: string,
  group: ItemGroup,
  w: number,
  d: number,
  h: number,
  where: string,
  priority: ToyPriority,
  o: Opts = {},
): ItemDef & { priority: ToyPriority } {
  return {
    id,
    name,
    group,
    w,
    d,
    h,
    where,
    variants: o.variants ?? 1,
    style: 'prop',
    paints: o.paints,
    map: 'toy',
    priority,
  };
}

/** Bow tie / scarf colours of the single-animal plush (the one `paint` part of the plush rig). */
const BOW = [0xd94a3a, 0x3b82d6, 0xf2c230, 0x4fa84a, 0xe86aa6, 0x8b5cd6];
/** Families of the plush rig that carry a bow (not the whale or the octopus). */
const BOWED =
  /^plush_(panda|brown_bear|gray_rabbit|elephant|unicorn|dino|penguin|giraffe|puppy|kitten|lion)_/;

export const TOY_DEFS: (ItemDef & { priority: ToyPriority })[] = [
  def(
    'minifigure',
    'Mini figure',
    'figures',
    0.12,
    0.1,
    0.3,
    'Figure Falls - 6 outfits (paint)',
    'P0',
    { variants: 1, paints: PRIMARY },
  ),
  def(
    'brick_2x2',
    'Brick 2x2',
    'bricks',
    0.16,
    0.16,
    0.1,
    'Brick Alley - 8 colours (paint)',
    'P0',
    { paints: PRIMARY },
  ),
  def(
    'bouncy_ball',
    'Bouncy ball',
    'toys',
    0.2,
    0.2,
    0.2,
    'everywhere - paint',
    'P0',
    { paints: PRIMARY },
  ),
  def(
    'spinning_top',
    'Spinning top',
    'games',
    0.2,
    0.2,
    0.25,
    'Game Room',
    'P1',
  ),
  def(
    'action_figure',
    'Action figure',
    'figures',
    0.25,
    0.15,
    0.6,
    'Figure Falls',
    'P0',
  ),
  def(
    'blind_bag',
    'Blind bag',
    'figures',
    0.25,
    0.04,
    0.35,
    'Checkout - foil packet, paint',
    'P1',
    { paints: PRIMARY },
  ),
  def(
    'alphabet_block',
    'ABC block',
    'toys',
    0.25,
    0.25,
    0.25,
    'Brick Alley',
    'P0',
  ),
  def(
    'animal_figure',
    'Farm animal figure',
    'figures',
    0.3,
    0.15,
    0.25,
    'Figure Falls - cow / pig / sheep variants',
    'P1',
    { variants: 3 },
  ),
  def(
    'rubber_duck',
    'Rubber duck',
    'toys',
    0.3,
    0.2,
    0.25,
    'Splash Zone',
    'P0',
  ),
  def(
    'puzzle_piece',
    'Puzzle piece',
    'games',
    0.3,
    0.3,
    0.03,
    'Game Room - flat, 4 colours',
    'P0',
  ),
  def(
    'plush_keychain',
    'Keychain plush',
    'plush',
    0.3,
    0.2,
    0.4,
    'Checkout - clip + ring',
    'P0',
  ),
  def(
    'doll_fashion',
    'Fashion doll',
    'dolls',
    0.3,
    0.15,
    0.9,
    'Doll House Lane - paint',
    'P1',
    { paints: PRIMARY },
  ),
  def(
    'brick_2x4',
    'Brick 2x4',
    'bricks',
    0.32,
    0.16,
    0.1,
    'Brick Alley - 8 colours (paint)',
    'P0',
    { paints: PRIMARY },
  ),
  def(
    'brick_plate',
    'Flat plate',
    'bricks',
    0.32,
    0.32,
    0.04,
    'Brick Alley - paint',
    'P0',
    { paints: PRIMARY },
  ),
  def(
    'figure_blister_pack',
    'Carded figure',
    'figures',
    0.35,
    0.1,
    0.55,
    'Figure Falls',
    'P1',
  ),
  def(
    'toy_car_mini',
    'Die-cast car',
    'toyveh',
    0.35,
    0.15,
    0.12,
    'Vroom Row - paint',
    'P0',
    { paints: PRIMARY },
  ),
  def(
    'wind_up_robot',
    'Wind-up robot',
    'robots',
    0.35,
    0.2,
    0.5,
    'Robot Factory - key on back',
    'P0',
  ),
  def(
    'dino_figure',
    'Dino figure',
    'figures',
    0.4,
    0.15,
    0.3,
    'Figure Falls',
    'P0',
  ),
  def('candy_jar', 'Candy jar', 'toys', 0.4, 0.4, 0.6, 'Checkout', 'P1'),
  def(
    'jack_in_box',
    'Jack-in-the-box',
    'games',
    0.4,
    0.4,
    0.6,
    'Game Room',
    'P1',
  ),
  def(
    'sand_bucket',
    'Bucket and spade',
    'outdoor',
    0.4,
    0.4,
    0.35,
    'Splash Zone',
    'P1',
  ),
  def(
    'soccer_ball',
    'Soccer ball',
    'outdoor',
    0.45,
    0.45,
    0.45,
    'Splash Zone',
    'P1',
  ),
  def(
    'brick_pile',
    'Handful of bricks',
    'bricks',
    0.5,
    0.5,
    0.2,
    'Brick Alley - filler, tops up the budget like grass tufts',
    'P0',
  ),
  def(
    'packing_peanuts',
    'Packing peanuts',
    'toys',
    0.5,
    0.5,
    0.25,
    'Stockroom - filler',
    'P0',
  ),
  def(
    'gumball_machine',
    'Gumball machine',
    'toys',
    0.5,
    0.5,
    0.95,
    'Checkout',
    'P1',
  ),
  def(
    'toy_basket',
    'Shopping basket',
    'toys',
    0.5,
    0.35,
    0.3,
    'everywhere - with toys',
    'P0',
  ),
  def(
    'baby_doll',
    'Baby doll',
    'dolls',
    0.5,
    0.35,
    0.5,
    'Doll House Lane',
    'P1',
  ),
  def(
    'puzzle_box',
    'Puzzle box',
    'games',
    0.5,
    0.4,
    0.08,
    'Game Room - box art colour blocks',
    'P0',
  ),
  def(
    'brick_tub',
    'Tub of bricks',
    'bricks',
    0.55,
    0.55,
    0.5,
    'Brick Alley - lid, studs on top',
    'P0',
  ),
  def(
    'confetti_pile',
    'Confetti',
    'toys',
    0.6,
    0.6,
    0.05,
    'everywhere - filler, flat',
    'P1',
  ),
  def(
    'balloon_bunch',
    'Balloons',
    'toys',
    0.6,
    0.6,
    1,
    'Checkout - weighted ribbon, paint',
    'P1',
    { paints: PRIMARY },
  ),
  def(
    'price_standee',
    'Price standee',
    'toys',
    0.6,
    0.3,
    1.5,
    'everywhere',
    'P1',
  ),
  def(
    'plush_penguin_s',
    'penguin plush',
    'plush',
    0.6,
    0.5,
    0.8,
    'Plush Meadow',
    'P1',
  ),
  def(
    'board_game_box',
    'Board game',
    'games',
    0.6,
    0.4,
    0.1,
    'Game Room - 4 colours',
    'P0',
  ),
  def(
    'cardboard_box',
    'Cardboard box',
    'store',
    0.6,
    0.5,
    0.5,
    'Stockroom',
    'P0',
  ),
  def('hand_truck', 'Hand truck', 'store', 0.6, 0.6, 1.3, 'Stockroom', 'P1'),
  def(
    'plush_panda_xs',
    'panda plush XS',
    'plush',
    0.7,
    0.6,
    0.9,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'board_game_stack',
    'Game stack',
    'games',
    0.7,
    0.5,
    0.9,
    'Game Room',
    'P1',
  ),
  def(
    'brick_set_box',
    'Brick set box',
    'bricks',
    0.8,
    0.6,
    0.2,
    'Brick Alley - box art = colour blocks',
    'P1',
  ),
  def(
    'spinner_rack',
    'Spinner rack',
    'toys',
    0.8,
    0.8,
    1.8,
    'Checkout - keychains / stickers',
    'P1',
  ),
  def(
    'plush_brown_bear_xs',
    'brown bear plush XS',
    'plush',
    0.8,
    0.7,
    1,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'plush_gray_rabbit_xs',
    'gray rabbit plush XS',
    'plush',
    0.8,
    0.6,
    1.4,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'plush_kitten_s',
    'kitten plush',
    'plush',
    0.8,
    0.5,
    0.8,
    'Plush Meadow',
    'P1',
  ),
  def(
    'robot_toy',
    'Toy robot',
    'robots',
    0.8,
    0.6,
    1.3,
    'Robot Factory - paint',
    'P0',
    { paints: PRIMARY },
  ),
  def('water_gun', 'Water gun', 'outdoor', 0.8, 0.2, 0.4, 'Splash Zone', 'P1'),
  def(
    'skateboard',
    'Skateboard',
    'outdoor',
    0.8,
    0.2,
    0.15,
    'Splash Zone',
    'P1',
  ),
  def(
    'plush_dino_s',
    'dino plush',
    'plush',
    0.9,
    0.6,
    0.9,
    'Plush Meadow',
    'P1',
  ),
  def(
    'plush_giraffe_s',
    'giraffe plush',
    'plush',
    0.9,
    0.5,
    2.8,
    'Plush Meadow',
    'P1',
  ),
  def(
    'plush_puppy_s',
    'puppy plush',
    'plush',
    0.9,
    0.5,
    0.7,
    'Plush Meadow',
    'P1',
  ),
  def(
    'beach_ball',
    'Beach ball',
    'outdoor',
    0.9,
    0.9,
    0.9,
    'Splash Zone - paint',
    'P0',
    { paints: PRIMARY },
  ),
  def(
    'figure_display_case',
    'Collector case',
    'figures',
    1,
    0.5,
    1.2,
    'Figure Falls - glass front, 3 shelves',
    'P1',
  ),
  def(
    'plush_unicorn_s',
    'unicorn plush',
    'plush',
    1,
    0.5,
    1.2,
    'Plush Meadow',
    'P1',
  ),
  def(
    'plush_pile',
    'Plush pile',
    'plush',
    1,
    1,
    0.8,
    'Plush Meadow - loose heap of minis, filler',
    'P0',
  ),
  def(
    'toy_truck',
    'Toy truck',
    'toyveh',
    1,
    0.5,
    0.5,
    'Vroom Row - paint',
    'P0',
    { paints: VEHICLE },
  ),
  def('drone', 'Toy drone', 'robots', 1, 1, 0.3, 'Robot Factory', 'P1'),
  def('arcade_cabinet', 'Arcade cabinet', 'games', 1, 1, 2, 'Game Room', 'P1'),
  def('tricycle', 'Tricycle', 'outdoor', 1, 0.5, 0.7, 'Splash Zone', 'P1'),
  def(
    'kick_scooter',
    'Kick scooter',
    'outdoor',
    1,
    0.4,
    1,
    'Splash Zone',
    'P1',
  ),
  def(
    'shopping_cart_toys',
    'Toy cart',
    'store',
    1,
    0.6,
    1,
    'everywhere - full of toys',
    'P0',
  ),
  def(
    'plush_panda_s',
    'panda plush S',
    'plush',
    1.1,
    1,
    1.4,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'doll_stroller',
    'Doll stroller',
    'dolls',
    1.1,
    0.6,
    1,
    'Doll House Lane',
    'P1',
  ),
  def(
    'brick_set_box_big',
    'Big set box',
    'bricks',
    1.2,
    0.9,
    0.25,
    'Brick Alley',
    'P1',
  ),
  def(
    'brick_car_small',
    'Brick car (small)',
    'bricks',
    1.2,
    0.6,
    0.5,
    'Brick Alley',
    'P1',
  ),
  def(
    'mascot_standee',
    'Mascot cut-out',
    'toys',
    1.2,
    0.4,
    3,
    'Atrium - card cut-out of the store mascot',
    'P1',
  ),
  def(
    'plush_elephant_s',
    'elephant plush',
    'plush',
    1.2,
    0.8,
    1,
    'Plush Meadow',
    'P1',
  ),
  def(
    'plush_octopus_s',
    'octopus plush',
    'plush',
    1.2,
    1.2,
    1,
    'Plush Meadow',
    'P1',
  ),
  def('giant_dice', 'Giant dice', 'games', 1.2, 1.2, 1.2, 'Game Room', 'P1'),
  def('chess_table', 'Chess table', 'games', 1.2, 1.2, 1, 'Game Room', 'P2'),
  def(
    'swim_ring',
    'Swim ring',
    'outdoor',
    1.2,
    1.2,
    0.3,
    'Splash Zone - paint',
    'P0',
    { paints: PRIMARY },
  ),
  def('ball_bin', 'Ball bin', 'outdoor', 1.2, 1.2, 1, 'Splash Zone', 'P1'),
  def('box_stack', 'Box stack', 'store', 1.2, 1.2, 2, 'Stockroom', 'P0'),
  def(
    'pallet_boxes',
    'Pallet of boxes',
    'store',
    1.2,
    1,
    1.6,
    'Stockroom',
    'P0',
  ),
  def(
    'end_cap_display',
    'End-cap display',
    'store',
    1.2,
    0.5,
    1.8,
    'everywhere',
    'P1',
  ),
  def(
    'brick_bin',
    'Open brick bin',
    'bricks',
    1.3,
    0.9,
    0.8,
    'Brick Alley - pick-a-brick wall bin, heaped with bricks',
    'P0',
  ),
  def(
    'plush_gray_rabbit_s',
    'gray rabbit plush S',
    'plush',
    1.3,
    0.9,
    2.3,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'toy_fire_truck',
    'Toy fire truck',
    'toyveh',
    1.3,
    0.5,
    0.6,
    'Vroom Row',
    'P1',
  ),
  def(
    'claw_machine',
    'Claw machine',
    'games',
    1.3,
    1.3,
    2.5,
    'Game Room - plush prizes baked in',
    'P0',
  ),
  def(
    'plush_brown_bear_s',
    'brown bear plush S',
    'plush',
    1.4,
    1.2,
    1.7,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'plush_bin',
    'Plush floor bin',
    'plush',
    1.4,
    1.4,
    1,
    'Plush Meadow',
    'P0',
  ),
  def(
    'tea_party_table',
    'Tea party set',
    'dolls',
    1.4,
    1.4,
    0.8,
    'Doll House Lane',
    'P1',
  ),
  def(
    'robot_action',
    'Action robot',
    'robots',
    1.4,
    1,
    2.2,
    'Robot Factory',
    'P0',
  ),
  def('plush_lion_s', 'lion plush', 'plush', 1.5, 1, 1.5, 'Plush Meadow', 'P1'),
  def(
    'dollhouse_small',
    'Dollhouse',
    'dolls',
    1.5,
    1.2,
    1.6,
    'Doll House Lane - open back, tiny furniture',
    'P0',
  ),
  def(
    'pinball_machine',
    'Pinball machine',
    'games',
    1.5,
    0.7,
    1.9,
    'Game Room',
    'P1',
  ),
  def(
    'foosball_table',
    'Foosball table',
    'games',
    1.5,
    0.8,
    1,
    'Game Room',
    'P1',
  ),
  def(
    'bike_kids',
    'Kids bike',
    'outdoor',
    1.5,
    0.5,
    0.9,
    'Splash Zone - paint',
    'P1',
    { paints: VEHICLE },
  ),
  def(
    'brick_baseplate_big',
    'Big baseplate',
    'bricks',
    1.6,
    1.6,
    0.1,
    'Brick Alley - floor build mat with a half-built model',
    'P1',
  ),
  def(
    'figure_shelf',
    'Figure wall shelf',
    'figures',
    1.6,
    0.5,
    1.6,
    'Figure Falls - stock baked in',
    'P0',
  ),
  def(
    'dino_figure_big',
    'Big dino model',
    'figures',
    1.6,
    0.6,
    1,
    'Figure Falls',
    'P1',
  ),
  def(
    'plush_penguin_m',
    'penguin plush',
    'plush',
    1.6,
    1.3,
    2,
    'Plush Meadow',
    'P1',
  ),
  def(
    'toy_kitchen',
    'Toy kitchen',
    'dolls',
    1.6,
    0.7,
    1.8,
    'Doll House Lane',
    'P1',
  ),
  def(
    'train_engine',
    'Toy train',
    'toyveh',
    1.6,
    0.5,
    0.8,
    'Vroom Row - engine + 2 wagons',
    'P1',
  ),
  def(
    'pool_float_duck',
    'Duck float',
    'outdoor',
    1.6,
    1.6,
    1.3,
    'Splash Zone',
    'P0',
  ),
  def(
    'display_table',
    'Display table',
    'store',
    1.6,
    1.2,
    0.8,
    'everywhere',
    'P0',
  ),
  def(
    'plush_kitten_m',
    'kitten plush',
    'plush',
    1.7,
    1,
    1.7,
    'Plush Meadow',
    'P1',
  ),
  def('rc_car', 'RC car', 'toyveh', 1.7, 0.9, 0.6, 'Vroom Row - paint', 'P0', {
    paints: VEHICLE,
  }),
  def(
    'plush_giraffe_m',
    'giraffe plush',
    'plush',
    1.8,
    1,
    5.5,
    'Plush Meadow',
    'P1',
  ),
  def(
    'rc_helicopter',
    'RC helicopter',
    'robots',
    1.8,
    0.5,
    0.6,
    'Robot Factory',
    'P2',
  ),
  def(
    'brick_house_small',
    'Brick house',
    'bricks',
    2,
    1.8,
    1.8,
    'Brick Alley',
    'P1',
  ),
  def(
    'plush_panda_m',
    'panda plush M',
    'plush',
    2,
    1.8,
    2.5,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def('plush_dino_m', 'dino plush', 'plush', 2, 1.3, 2, 'Plush Meadow', 'P1'),
  def('plush_puppy_m', 'puppy plush', 'plush', 2, 1, 1.6, 'Plush Meadow', 'P1'),
  def(
    'rc_monster_truck',
    'RC monster truck',
    'toyveh',
    2,
    1.4,
    1,
    'Vroom Row',
    'P1',
  ),
  def('robot_dog', 'Robot dog', 'robots', 2, 0.9, 1.4, 'Robot Factory', 'P1'),
  def(
    'floor_puzzle_mat',
    'Floor puzzle',
    'games',
    2,
    1.5,
    0.05,
    'Game Room - flat',
    'P2',
  ),
  def(
    'pool_float_swan',
    'Swan float',
    'outdoor',
    2,
    1.4,
    1.8,
    'Splash Zone',
    'P1',
  ),
  def('shipping_crate', 'Shipping crate', 'store', 2, 2, 2, 'Stockroom', 'P1'),
  def(
    'plush_unicorn_m',
    'unicorn plush',
    'plush',
    2.2,
    1.1,
    2.6,
    'Plush Meadow',
    'P1',
  ),
  def(
    'pool_float_flamingo',
    'Flamingo float',
    'outdoor',
    2.2,
    1.8,
    1.8,
    'Splash Zone',
    'P0',
  ),
  def(
    'pool_float_donut',
    'Donut float',
    'outdoor',
    2.2,
    2.2,
    0.7,
    'Splash Zone - paint',
    'P1',
    { paints: PASTEL },
  ),
  def(
    'figure_gondola',
    'Figure gondola',
    'figures',
    2.4,
    0.7,
    2,
    'Figure Falls - carded figures both sides',
    'P0',
  ),
  def(
    'plush_gray_rabbit_m',
    'gray rabbit plush M',
    'plush',
    2.4,
    1.6,
    4.2,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'plush_wall_shelf',
    'Plush shelf unit',
    'plush',
    2.4,
    0.8,
    2,
    'Plush Meadow - stock baked in',
    'P0',
  ),
  def('toy_plane', 'Toy plane', 'toyveh', 2.4, 2.4, 0.8, 'Vroom Row', 'P1'),
  def(
    'robot_big',
    'Big robot',
    'robots',
    2.4,
    1.8,
    4,
    'Robot Factory - paint',
    'P0',
    { paints: PRIMARY },
  ),
  def(
    'air_hockey_table',
    'Air hockey',
    'games',
    2.4,
    1.3,
    0.9,
    'Game Room',
    'P1',
  ),
  def(
    'game_shelf',
    'Board game shelf',
    'games',
    2.4,
    0.6,
    2,
    'Game Room',
    'P1',
  ),
  def(
    'pool_float_unicorn',
    'Unicorn float',
    'outdoor',
    2.4,
    1.8,
    2,
    'Splash Zone',
    'P1',
  ),
  def(
    'paddling_pool',
    'Paddling pool',
    'outdoor',
    2.4,
    2.4,
    0.5,
    'Splash Zone',
    'P1',
  ),
  def('kids_goal', 'Kids goal', 'outdoor', 2.4, 1.2, 1.6, 'Splash Zone', 'P2'),
  def(
    'gondola_shelf',
    'Gondola shelf',
    'store',
    2.4,
    0.7,
    2,
    'everywhere - stock variant per department',
    'P0',
    { variants: 5 },
  ),
  def(
    'checkout_counter',
    'Checkout counter',
    'store',
    2.4,
    0.9,
    1,
    'Checkout',
    'P1',
  ),
  def('box_pyramid', 'Box pyramid', 'store', 2.4, 2.4, 2, 'Stockroom', 'P1'),
  def(
    'play_tent',
    'Play tent',
    'dolls',
    2.5,
    2.5,
    2.2,
    'Doll House Lane - paint',
    'P1',
    { paints: PRIMARY },
  ),
  def('forklift', 'Forklift', 'store', 2.5, 1.2, 2.2, 'Stockroom', 'P1'),
  def(
    'plush_brown_bear_m',
    'brown bear plush M',
    'plush',
    2.6,
    2.3,
    3.2,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'plush_whale_s',
    'whale plush',
    'plush',
    2.8,
    1.2,
    1.6,
    'Plush Meadow',
    'P1',
  ),
  def(
    'brick_dragon',
    'Brick dragon',
    'bricks',
    3,
    1.5,
    2.5,
    'Brick Alley',
    'P2',
  ),
  def(
    'dino_diorama',
    'Dino diorama',
    'figures',
    3,
    2,
    1.2,
    'Figure Falls',
    'P2',
  ),
  def(
    'plush_elephant_m',
    'elephant plush',
    'plush',
    3,
    2,
    2.5,
    'Plush Meadow',
    'P1',
  ),
  def(
    'plush_octopus_m',
    'octopus plush',
    'plush',
    3,
    3,
    2.4,
    'Plush Meadow',
    'P1',
  ),
  def(
    'train_set_loop',
    'Train set loop',
    'toyveh',
    3,
    3,
    0.5,
    'Vroom Row',
    'P1',
  ),
  def(
    'plush_lion_m',
    'lion plush',
    'plush',
    3.2,
    2.2,
    3.2,
    'Plush Meadow',
    'P1',
  ),
  def(
    'ride_on_car',
    'Ride-on car',
    'toyveh',
    3.2,
    1.6,
    1.8,
    'Vroom Row - paint',
    'P0',
    { paints: VEHICLE },
  ),
  def(
    'inflatable_raft',
    'Inflatable raft',
    'outdoor',
    3.2,
    1.9,
    0.6,
    'Splash Zone - paint, oars',
    'P0',
    { paints: VEHICLE },
  ),
  def(
    'figure_pyramid',
    'Figure pyramid',
    'figures',
    3.4,
    3.4,
    2.4,
    'Figure Falls - tiered promo display',
    'P1',
  ),
  def(
    'plush_penguin_l',
    'penguin plush',
    'plush',
    3.4,
    2.8,
    4.2,
    'Plush Meadow',
    'P1',
  ),
  def(
    'robo_truck',
    'Robo-truck',
    'robots',
    3.4,
    1.8,
    3,
    'Robot Factory - half truck, half robot',
    'P1',
  ),
  def(
    'inflatable_kayak',
    'Inflatable kayak',
    'outdoor',
    3.4,
    0.9,
    0.5,
    'Splash Zone',
    'P2',
  ),
  def(
    'trampoline',
    'Trampoline',
    'outdoor',
    3.4,
    3.4,
    0.9,
    'Splash Zone',
    'P1',
  ),
  def(
    'backyard_slide',
    'Garden slide',
    'outdoor',
    3.4,
    1,
    2.2,
    'Splash Zone',
    'P2',
  ),
  def(
    'plush_giraffe_l',
    'giraffe plush',
    'plush',
    3.5,
    2,
    11,
    'Plush Meadow',
    'P1',
  ),
  def(
    'plush_pyramid',
    'Plush pyramid',
    'plush',
    3.5,
    3.5,
    3,
    'Plush Meadow - stacked mixed plush',
    'P1',
  ),
  def(
    'race_track_set',
    'Race track set',
    'toyveh',
    3.5,
    2.5,
    2,
    'Vroom Row - loop-the-loop',
    'P1',
  ),
  def(
    'plush_panda_l',
    'panda plush L',
    'plush',
    4,
    3.6,
    5,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def('plush_puppy_l', 'puppy plush', 'plush', 4, 2, 3.2, 'Plush Meadow', 'P1'),
  def(
    'ball_pit',
    'Ball pit',
    'games',
    4,
    4,
    1,
    'Game Room - balls baked in',
    'P1',
  ),
  def(
    'ride_on_jeep',
    'Ride-on jeep',
    'toyveh',
    4.1,
    1.9,
    2,
    'Vroom Row - paint',
    'P1',
    { paints: VEHICLE },
  ),
  def(
    'brick_car_big',
    'Brick sports car',
    'bricks',
    4.4,
    2,
    1.6,
    'Brick Alley - display model',
    'P1',
  ),
  def(
    'plush_unicorn_l',
    'unicorn plush',
    'plush',
    4.4,
    2.2,
    5.2,
    'Plush Meadow',
    'P1',
  ),
  def(
    'dollhouse_large',
    'Large dollhouse',
    'dolls',
    4.5,
    3.5,
    4.5,
    'Doll House Lane',
    'P1',
  ),
  def(
    'storefront_kiosk',
    'Impulse kiosk',
    'store',
    4.5,
    3.5,
    3,
    'Checkout',
    'P2',
  ),
  def(
    'plush_gray_rabbit_l',
    'gray rabbit plush L',
    'plush',
    4.6,
    3.2,
    8,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'go_kart',
    'Go-kart',
    'toyveh',
    4.6,
    2.2,
    1.6,
    'Vroom Row - paint',
    'P1',
    { paints: VEHICLE },
  ),
  def(
    'raft_family',
    'Family raft',
    'outdoor',
    4.8,
    2.4,
    0.9,
    'Splash Zone - paint',
    'P0',
    { paints: VEHICLE },
  ),
  def('plush_dino_l', 'dino plush', 'plush', 5, 3, 4.5, 'Plush Meadow', 'P1'),
  def('toy_castle', 'Toy castle', 'dolls', 5, 5, 5, 'Doll House Lane', 'P1'),
  def('rocket_display', 'Rocket', 'robots', 5, 5, 14, 'Robot Factory', 'P1'),
  def(
    'plush_brown_bear_l',
    'brown bear plush L',
    'plush',
    5.2,
    4.6,
    6.4,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'ride_on_fire_engine',
    'Ride-on fire engine',
    'toyveh',
    5.2,
    2.2,
    3,
    'Vroom Row',
    'P1',
  ),
  def(
    'playhouse_cottage',
    'Garden playhouse',
    'dolls',
    5.5,
    4.5,
    4,
    'Splash Zone',
    'P1',
  ),
  def('robot_giant', 'Giant robot', 'robots', 5.5, 4, 9, 'Robot Factory', 'P0'),
  def(
    'plush_throne',
    'Plush throne',
    'plush',
    6,
    6,
    6,
    'Plush Meadow - giant armchair with plush audience',
    'P2',
  ),
  def(
    'pool_float_whale',
    'Whale float',
    'outdoor',
    6,
    3,
    2.5,
    'Splash Zone',
    'P1',
  ),
  def(
    'inflatable_pool_big',
    'Inflatable pool',
    'outdoor',
    6,
    6,
    1.2,
    'Splash Zone',
    'P2',
  ),
  def(
    'plush_elephant_l',
    'elephant plush',
    'plush',
    6.5,
    4.4,
    5.5,
    'Plush Meadow',
    'P1',
  ),
  def(
    'ride_on_helicopter',
    'Ride-on helicopter',
    'toyveh',
    6.5,
    2,
    3,
    'Vroom Row',
    'P2',
  ),
  def('carousel_mini', 'Mini carousel', 'toyveh', 6.5, 6.5, 5, 'Atrium', 'P1'),
  def(
    'bounce_house',
    'Bounce house',
    'outdoor',
    6.5,
    6.5,
    5,
    'Splash Zone - paint',
    'P1',
    { paints: PRIMARY },
  ),
  def('plush_whale_m', 'whale plush', 'plush', 7, 3, 4, 'Plush Meadow', 'P1'),
  def(
    'shelf_run',
    'Shelf run',
    'store',
    7,
    0.8,
    2.2,
    'everywhere - 3 gondolas joined',
    'P1',
  ),
  def(
    'delivery_truck_box',
    'Delivery truck',
    'store',
    7,
    2.6,
    3.6,
    'Stockroom',
    'P0',
  ),
  def(
    'plush_panda_xl',
    'panda plush XL',
    'plush',
    8,
    7.2,
    10,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'kiddie_train_ride',
    'Kiddie train ride',
    'toyveh',
    8,
    2.2,
    3.5,
    'Vroom Row',
    'P2',
  ),
  def(
    'ferris_wheel_mini',
    'Mini Ferris wheel',
    'toyveh',
    8,
    3,
    10,
    'Atrium',
    'P2',
  ),
  def(
    'giant_board_game',
    'Giant board game',
    'games',
    8,
    8,
    0.1,
    'Game Room - floor game, flat',
    'P2',
  ),
  def(
    'plush_unicorn_xl',
    'unicorn plush',
    'plush',
    8.5,
    4.2,
    10,
    'Plush Meadow',
    'P1',
  ),
  def(
    'spaceship_display',
    'Spaceship',
    'robots',
    8.5,
    6,
    4,
    'Robot Factory',
    'P2',
  ),
  def(
    'plush_gray_rabbit_xl',
    'gray rabbit plush XL',
    'plush',
    9,
    6,
    15.5,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'dollhouse_mansion',
    'Dollhouse mansion',
    'dolls',
    9,
    6.5,
    8,
    'Doll House Lane',
    'P2',
  ),
  def('rocket_big', 'Big rocket', 'robots', 9, 9, 28, 'Robot Factory', 'P1'),
  def(
    'robot_mech_walker',
    'Mech walker',
    'robots',
    9,
    7,
    14,
    'Robot Factory',
    'P1',
  ),
  def(
    'aisle_shelf_double',
    'Double aisle shelf',
    'store',
    9.6,
    1.6,
    2.4,
    'everywhere',
    'P2',
  ),
  def('plush_dino_xl', 'dino plush', 'plush', 10, 6, 9, 'Plush Meadow', 'P1'),
  def(
    'plush_brown_bear_xl',
    'brown bear plush XL',
    'plush',
    11,
    9.6,
    13.5,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'play_castle_big',
    'Play castle',
    'dolls',
    11,
    11,
    9,
    'Doll House Lane',
    'P1',
  ),
  def(
    'brick_tower_display',
    'Brick tower',
    'landmark',
    12,
    12,
    30,
    'Atrium - studded corner tower',
    'P1',
  ),
  def(
    'carousel_big',
    'Carousel',
    'toyveh',
    12,
    12,
    8,
    'Atrium - animated spin = iteration',
    'P1',
  ),
  def(
    'shipping_container',
    'Shipping container',
    'store',
    12,
    2.4,
    2.6,
    'Stockroom',
    'P1',
  ),
  def(
    'plush_elephant_xl',
    'elephant plush',
    'plush',
    13,
    9,
    11,
    'Plush Meadow',
    'P1',
  ),
  def('railway_table', 'Railway table', 'toyveh', 14, 9, 3, 'Vroom Row', 'P1'),
  def('robot_colossus', 'Colossus robot', 'robots', 14, 10, 30, 'Atrium', 'P0'),
  def(
    'giant_inflatable_slide',
    'Inflatable slide',
    'outdoor',
    14,
    5,
    8,
    'Splash Zone',
    'P2',
  ),
  def('semi_trailer', 'Semi trailer', 'store', 14, 2.6, 4, 'Stockroom', 'P1'),
  def(
    'plush_panda_xxl',
    'panda plush XXL',
    'plush',
    15,
    13.5,
    19,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'brick_skyscraper_display',
    'Brick skyscraper',
    'landmark',
    16,
    16,
    40,
    'Atrium',
    'P2',
  ),
  def(
    'plush_gray_rabbit_xxl',
    'gray rabbit plush XXL',
    'plush',
    17,
    11,
    30,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'dino_statue_trex',
    'T-rex statue',
    'landmark',
    18,
    6,
    10,
    'Atrium',
    'P2',
  ),
  def(
    'ferris_wheel_giant',
    'Ferris wheel',
    'toyveh',
    20,
    6,
    24,
    'Atrium',
    'P1',
  ),
  def(
    'giant_gift_box',
    'Giant gift box',
    'landmark',
    20,
    20,
    20,
    'Atrium',
    'P2',
  ),
  def(
    'brick_castle_display',
    'Brick castle',
    'landmark',
    22,
    22,
    14,
    'Atrium - banners, drawbridge',
    'P1',
  ),
  def(
    'plush_brown_bear_xxl',
    'brown bear plush XXL',
    'plush',
    22,
    19,
    27,
    'Plush Meadow - REQUIRED family',
    'P0',
  ),
  def(
    'plush_whale_xxl',
    'Whale plush XXL',
    'plush',
    24,
    10,
    13,
    'Atrium - hangs over the aisle',
    'P2',
  ),
  def(
    'rocket_giant',
    'Giant rocket',
    'landmark',
    24,
    24,
    70,
    'Atrium - fins + gantry',
    'P2',
  ),
  def(
    'model_railway',
    'Model railway',
    'toyveh',
    28,
    18,
    6,
    'Vroom Row - tunnels, station, little town',
    'P2',
  ),
  def('robot_titan', 'Titan robot', 'landmark', 28, 20, 55, 'Atrium', 'P1'),
  def(
    'dino_statue_brachio',
    'Long-neck statue',
    'landmark',
    30,
    5,
    20,
    'Atrium',
    'P2',
  ),
  def(
    'robot_overlord',
    'Overlord robot',
    'landmark',
    34,
    26,
    66,
    'Atrium - tier 25 centrepiece',
    'P1',
  ),
  def(
    'railway_world',
    'Railway world',
    'landmark',
    34,
    22,
    7,
    'Vroom Row - whole town on a table',
    'P2',
  ),
  def(
    'landmark_big_ted',
    'Big Ted',
    'landmark',
    34,
    30,
    40,
    'Atrium - the signature landmark, 1 copy',
    'P0',
  ),
];

for (const d of TOY_DEFS)
  if (
    BOWED.test(d.id) ||
    d.id === 'plush_keychain' ||
    d.id === 'landmark_big_ted'
  )
    d.paints = BOW;
