import type { ItemDef } from './catalog';
import type { MoveKind } from '../map/types';

/**
 * Animal Island edible catalog (the third map). Data only: size, tier, level and points are derived from
 * the dimensions in catalog.ts like every other item. Priority P0 = first playable set, P1 = full v1,
 * P2 = polish (see ANIMAL-ISLAND.md). `biomes` = where the generator may place it, `motion` = how it moves
 * ('herd' walks like 'wander' but is placed in groups; '-' = static). Builders: build-animals.ts (rigs),
 * build-nature.ts (flora, rocks, hills), build-zoo.ts (zoo, farm, laboratory). Nine greenery items
 * (flower, grass_tuft, bush_small, bush_large, tree_small, palm_tree, hedge, tree, tree_big) are shared with City Island.
 */
export type Biome =
  | 'meadow'
  | 'forest'
  | 'savanna'
  | 'wetland'
  | 'highlands'
  | 'beach'
  | 'jungle'
  | 'zoo'
  | 'lab'
  | 'farm'
  | 'river'
  | 'bank'
  | 'everywhere';
export type Motion = MoveKind | 'herd' | '-';
export type AnimalPriority = 'P0' | 'P1' | 'P2';
export type AnimalDef = ItemDef & {
  priority: AnimalPriority;
  biomes: Biome[];
  motion: Motion;
};

/** City items the animal map uses as they are (identical sizes). */
export const SHARED_CITY_IDS = [
  'flower',
  'grass_tuft',
  'bush_small',
  'bush_large',
  'tree_small',
  'palm_tree',
  'hedge',
  'tree',
  'tree_big',
];

const RED_Y = [0xd94a3a, 0xf2c230, 0xf08a2b];
const BEETLE = [0x4fa84a, 0x3b82d6, 0xb07a3a];
const CATER = [0x7ec850, 0xf2c230, 0xf08a2b];
const WINGS = [0xf08a2b, 0x3b82d6, 0xe86aa6, 0xf2c230];
const FUR_GREY = [0x9a9a9a, 0x8a6a4a];
const FROG = [0x4fa84a, 0x7ec850, 0x2f9a8a];
const MONKEY = [0x7a5230, 0xd9a441];
const PARROT = [0xd94a3a, 0x3b82d6, 0x4fa84a];
const WOOL = [0xf4f1ea, 0xf3e3c3, 0x4b4540];
const HORSE = [0x8a5a35, 0xb06a3a, 0x2b2b2e, 0xf2f2f2];
const WOOL2 = [0xf4f1ea, 0x9a7a55, 0xb0b0b0];
const CAPS = [0xd94a3a, 0xa8743f, 0xf2c230];
const BERRY = [0xd94a3a, 0x3b5bd6, 0x8b5cd6];
const PADS = [0x58b04c, 0x6cc25a, 0x3c8a3e];
const SHELL = [0xf5d9c8, 0xf0b8a0, 0xffffff];
const STAR = [0xf08a2b, 0xd94a3a, 0xf2c230];
const BOX = [0xd94a3a, 0x3b82d6, 0x4fa84a, 0xf2c230];
const FUR_DARK = [0x3a3f45, 0x5a4a3a];
const COAT = [0xf4f1ea, 0xe8f0f4];
const KHAKI = [0xb8a070, 0x8a9a5a];
const JEEP = [0xf2f2f2, 0x4fa84a, 0xf2c230];

/** Window material of the lab buildings (the walls tile windows); everything else is plain vertex colour. */
const STYLE: Record<string, ItemDef['style']> = {
  greenhouse: 'glass',
  biodome: 'glass',
  lab_block: 'punched',
  lab_wing: 'ribbon',
  lab_hq: 'glass',
  lab_tower: 'ribbon',
};

type Opts = Partial<Pick<ItemDef, 'variants' | 'paints'>>;

function def(
  id: string,
  name: string,
  group: ItemDef['group'],
  w: number,
  d: number,
  h: number,
  where: string,
  priority: AnimalPriority,
  biomes: Biome[],
  motion: Motion,
  o: Opts = {},
): AnimalDef {
  return {
    id,
    name,
    group,
    w,
    d,
    h,
    where,
    variants: o.variants ?? 1,
    style: STYLE[id] ?? 'prop',
    paints: o.paints,
    map: 'animal',
    priority,
    biomes,
    motion,
  };
}

export const ANIMAL_DEFS: AnimalDef[] = [
  def(
    'ant',
    'Ant',
    'bugs',
    0.15,
    0.06,
    0.05,
    'marches in columns between anthills and food',
    'P0',
    ['meadow', 'forest'],
    'trail',
  ),
  def(
    'ant_soldier',
    'Ant soldier',
    'bugs',
    0.25,
    0.1,
    0.08,
    'big head and jaws, guards the anthill',
    'P1',
    ['meadow', 'forest'],
    'trail',
  ),
  def(
    'ladybug',
    'Ladybug',
    'bugs',
    0.18,
    0.14,
    0.08,
    'paint: red / yellow / orange shell, black dots',
    'P0',
    ['meadow'],
    'skitter',
    { paints: RED_Y },
  ),
  def(
    'beetle',
    'Beetle',
    'bugs',
    0.3,
    0.18,
    0.12,
    'paint: green / blue / bronze shell; ladder: beetle -> beetle_big -> beetle_giant',
    'P0',
    ['forest'],
    'skitter',
    { paints: BEETLE },
  ),
  def(
    'grasshopper',
    'Grasshopper',
    'bugs',
    0.35,
    0.1,
    0.15,
    'long back legs',
    'P0',
    ['meadow', 'savanna'],
    'hop',
  ),
  def(
    'caterpillar',
    'Caterpillar',
    'bugs',
    0.3,
    0.06,
    0.06,
    '5 segments, paint',
    'P1',
    ['meadow', 'forest'],
    'crawl',
    { paints: CATER },
  ),
  def(
    'snail',
    'Snail',
    'bugs',
    0.22,
    0.1,
    0.15,
    'swirl shell (stacked boxes); ladder: snail -> snail_giant',
    'P0',
    ['meadow', 'wetland'],
    'crawl',
  ),
  def(
    'butterfly',
    'Butterfly',
    'bugs',
    0.3,
    0.25,
    0.1,
    'paint wings; flutters 0.3-1 m above the ground (y bob)',
    'P1',
    ['meadow'],
    'flutter',
    { paints: WINGS },
  ),
  def(
    'bee',
    'Bee',
    'bugs',
    0.15,
    0.12,
    0.1,
    'circles its beehive',
    'P1',
    ['meadow', 'farm'],
    'flutter',
  ),
  def(
    'spider',
    'Spider',
    'bugs',
    0.3,
    0.3,
    0.1,
    'cartoon, 8 legs, big eyes (not scary)',
    'P2',
    ['forest', 'jungle'],
    'skitter',
  ),
  def(
    'dragonfly',
    'Dragonfly',
    'bugs',
    0.35,
    0.3,
    0.06,
    'hovers over the water',
    'P2',
    ['wetland', 'river'],
    'flutter',
  ),
  def(
    'mouse',
    'Mouse',
    'critters',
    0.2,
    0.08,
    0.1,
    'paint grey / brown; ladder: mouse -> mouse_giant',
    'P0',
    ['meadow', 'farm'],
    'skitter',
    { paints: FUR_GREY },
  ),
  def(
    'lab_mouse',
    'Lab mouse',
    'critters',
    0.2,
    0.08,
    0.1,
    'white, glowing ear tag',
    'P1',
    ['lab'],
    'skitter',
  ),
  def(
    'frog',
    'Frog',
    'critters',
    0.25,
    0.2,
    0.15,
    'paint; ladder: frog -> frog_big -> frog_giant',
    'P0',
    ['wetland', 'river'],
    'hop',
    { paints: FROG },
  ),
  def(
    'chick',
    'Chick',
    'critters',
    0.18,
    0.12,
    0.15,
    'follows a hen',
    'P0',
    ['farm'],
    'wander',
  ),
  def(
    'hen',
    'Hen',
    'critters',
    0.45,
    0.25,
    0.45,
    'pecks (head bob); ladder: hen -> chicken_giant',
    'P0',
    ['farm'],
    'wander',
  ),
  def(
    'rooster',
    'Rooster',
    'critters',
    0.5,
    0.25,
    0.6,
    'red comb, tail',
    'P1',
    ['farm'],
    'wander',
  ),
  def(
    'duck',
    'Duck',
    'critters',
    0.45,
    0.25,
    0.4,
    'swims along the river',
    'P0',
    ['river', 'wetland'],
    'swim',
  ),
  def(
    'duckling',
    'Duckling',
    'critters',
    0.2,
    0.12,
    0.18,
    'in a line behind a duck',
    'P1',
    ['river', 'wetland'],
    'swim',
  ),
  def(
    'squirrel',
    'Squirrel',
    'critters',
    0.45,
    0.15,
    0.3,
    'big curled tail',
    'P0',
    ['forest'],
    'skitter',
  ),
  def(
    'hedgehog',
    'Hedgehog',
    'critters',
    0.3,
    0.2,
    0.18,
    'spikes as a stepped dome',
    'P0',
    ['forest', 'meadow'],
    'wander',
  ),
  def(
    'rabbit',
    'Rabbit',
    'critters',
    0.45,
    0.25,
    0.4,
    'ladder: rabbit -> rabbit_big -> rabbit_giant',
    'P0',
    ['meadow'],
    'hop',
  ),
  def(
    'meerkat',
    'Meerkat',
    'critters',
    0.3,
    0.12,
    0.4,
    'stands up when idle (pose variant)',
    'P1',
    ['savanna'],
    'wander',
  ),
  def(
    'monkey',
    'Monkey',
    'critters',
    0.6,
    0.3,
    0.6,
    'long tail, paint brown / gold',
    'P0',
    ['jungle'],
    'wander',
    { paints: MONKEY },
  ),
  def(
    'parrot',
    'Parrot',
    'critters',
    0.4,
    0.2,
    0.4,
    'paint red / blue / green',
    'P1',
    ['jungle'],
    'wander',
    { paints: PARROT },
  ),
  def(
    'crab',
    'Crab',
    'critters',
    0.35,
    0.25,
    0.12,
    'walks sideways',
    'P0',
    ['beach'],
    'skitter',
  ),
  def(
    'seagull',
    'Seagull',
    'critters',
    0.45,
    0.3,
    0.35,
    '',
    'P1',
    ['beach'],
    'wander',
  ),
  def(
    'penguin',
    'Penguin',
    'critters',
    0.5,
    0.4,
    0.7,
    'waddle (roll sway)',
    'P1',
    ['beach'],
    'wander',
  ),
  def('otter', 'Otter', 'critters', 0.8, 0.2, 0.3, '', 'P1', ['river'], 'swim'),
  def(
    'beaver',
    'Beaver',
    'critters',
    0.85,
    0.3,
    0.35,
    'flat tail, near the beaver dam',
    'P1',
    ['river', 'wetland'],
    'wander',
  ),
  def(
    'fox',
    'Fox',
    'critters',
    0.85,
    0.25,
    0.45,
    'orange, white tail tip',
    'P0',
    ['forest', 'meadow'],
    'wander',
  ),
  def(
    'raccoon',
    'Raccoon',
    'critters',
    0.7,
    0.3,
    0.4,
    'striped tail, mask',
    'P1',
    ['forest'],
    'wander',
  ),
  def(
    'flamingo',
    'Flamingo',
    'critters',
    0.5,
    0.3,
    1.3,
    'pink, flocks in shallow water',
    'P1',
    ['wetland'],
    'herd',
  ),
  def(
    'heron',
    'Heron',
    'critters',
    0.6,
    0.3,
    1,
    'grey, long legs',
    'P2',
    ['wetland', 'river'],
    'wander',
  ),
  def(
    'owl',
    'Owl',
    'critters',
    0.3,
    0.3,
    0.5,
    'sits on a stump',
    'P2',
    ['forest'],
    '-',
  ),
  def(
    'mushroom',
    'Mushroom',
    'flora',
    0.2,
    0.2,
    0.25,
    'paint red / brown cap',
    'P0',
    ['forest'],
    '-',
    { paints: CAPS },
  ),
  def(
    'dandelion',
    'Dandelion',
    'flora',
    0.2,
    0.2,
    0.4,
    'white puff head',
    'P1',
    ['meadow'],
    '-',
  ),
  def(
    'clover',
    'Clover',
    'flora',
    0.3,
    0.3,
    0.1,
    '1-point filler',
    'P1',
    ['meadow'],
    '-',
  ),
  def(
    'fern',
    'Fern',
    'flora',
    0.6,
    0.6,
    0.5,
    '',
    'P0',
    ['forest', 'jungle'],
    '-',
  ),
  def(
    'reeds',
    'Reeds',
    'flora',
    0.5,
    0.5,
    1.4,
    '',
    'P0',
    ['wetland', 'bank'],
    '-',
  ),
  def(
    'cattail',
    'Cattail',
    'flora',
    0.4,
    0.4,
    1.6,
    'brown heads',
    'P1',
    ['wetland'],
    '-',
  ),
  def(
    'lily_pad',
    'Lily pad',
    'flora',
    0.5,
    0.5,
    0.03,
    'stands ON the water; paint (some with a pink flower)',
    'P0',
    ['river'],
    '-',
    { paints: PADS },
  ),
  def(
    'pebble',
    'Pebble',
    'rocks',
    0.3,
    0.25,
    0.15,
    '1-point filler',
    'P0',
    ['everywhere'],
    '-',
  ),
  def(
    'seashell',
    'Seashell',
    'rocks',
    0.2,
    0.2,
    0.1,
    'paint',
    'P1',
    ['beach'],
    '-',
    { paints: SHELL },
  ),
  def(
    'starfish',
    'Starfish',
    'rocks',
    0.3,
    0.3,
    0.05,
    'paint',
    'P1',
    ['beach'],
    '-',
    { paints: STAR },
  ),
  def(
    'egg_nest',
    'Egg nest',
    'flora',
    0.4,
    0.4,
    0.2,
    '3 eggs in twigs',
    'P1',
    ['meadow', 'forest'],
    '-',
  ),
  def(
    'beehive',
    'Beehive',
    'farm',
    0.6,
    0.6,
    1,
    'box hive on legs, bees circle it',
    'P1',
    ['meadow', 'farm'],
    '-',
  ),
  def(
    'molehill',
    'Molehill',
    'hills',
    0.6,
    0.6,
    0.25,
    'hill ladder, rung 1',
    'P0',
    ['meadow'],
    '-',
    { variants: 3 },
  ),
  def(
    'anthill',
    'Anthill',
    'hills',
    0.8,
    0.8,
    0.6,
    'ant trails start here',
    'P0',
    ['meadow', 'forest'],
    '-',
    { variants: 3 },
  ),
  def(
    'scientist',
    'Scientist',
    'staff',
    0.5,
    0.35,
    1.75,
    'white coat, clipboard; walks between lab doors',
    'P0',
    ['lab', 'zoo'],
    'patrol',
    { paints: COAT },
  ),
  def(
    'zookeeper',
    'Zookeeper',
    'staff',
    0.5,
    0.35,
    1.75,
    'khaki overalls, bucket',
    'P0',
    ['zoo'],
    'patrol',
    { paints: KHAKI },
  ),
  def(
    'serum_barrel',
    'Serum barrel',
    'lab',
    0.6,
    0.6,
    0.9,
    'glowing green band (glow)',
    'P0',
    ['lab'],
    '-',
  ),
  def(
    'warning_sign',
    'Warning sign',
    'lab',
    0.6,
    0.1,
    1.5,
    'generic hazard triangle with a paw print (no real logos)',
    'P0',
    ['zoo', 'lab'],
    '-',
  ),
  def(
    'camera_pole',
    'Camera pole',
    'lab',
    0.3,
    0.3,
    3,
    'security camera, red glow dot',
    'P1',
    ['lab'],
    '-',
  ),
  def(
    'feed_bucket',
    'Feed bucket',
    'zoo',
    0.4,
    0.4,
    0.4,
    '',
    'P1',
    ['zoo'],
    '-',
  ),
  def(
    'lab_cart',
    'Lab cart',
    'lab',
    0.85,
    0.5,
    1,
    'trolley with glowing sample tubes',
    'P1',
    ['lab'],
    '-',
    { paints: BOX },
  ),
  def(
    'tortoise',
    'Tortoise',
    'animals',
    1,
    0.7,
    0.5,
    'ladder: tortoise -> tortoise_big -> tortoise_giant',
    'P0',
    ['meadow', 'savanna'],
    'crawl',
  ),
  def(
    'lamb',
    'Lamb',
    'animals',
    1,
    0.4,
    0.8,
    'follows a sheep',
    'P1',
    ['highlands', 'farm'],
    'herd',
  ),
  def('hay_bale', 'Hay bale', 'farm', 1, 1, 1, '', 'P0', ['farm', 'zoo'], '-'),
  def(
    'boulder_small',
    'Boulder small',
    'rocks',
    1,
    0.9,
    0.7,
    '',
    'P0',
    ['highlands', 'beach'],
    '-',
  ),
  def(
    'tree_stump',
    'Tree stump',
    'flora',
    1,
    1,
    0.6,
    'rings on top',
    'P0',
    ['forest'],
    '-',
  ),
  def(
    'feeding_trough',
    'Feeding trough',
    'zoo',
    1,
    0.5,
    0.5,
    '',
    'P0',
    ['zoo', 'farm'],
    '-',
  ),
  def(
    'lab_crate',
    'Lab crate',
    'lab',
    1,
    1,
    1,
    'crate with a paw-print mark (no text)',
    'P0',
    ['lab'],
    '-',
  ),
  def(
    'goat',
    'Goat',
    'animals',
    1.15,
    0.4,
    0.95,
    'horns; grazes between the hills',
    'P0',
    ['highlands'],
    'herd',
  ),
  def(
    'sheep',
    'Sheep',
    'animals',
    1.2,
    0.6,
    1,
    'woolly stepped body, paint white / cream / black',
    'P0',
    ['highlands', 'meadow'],
    'herd',
    { paints: WOOL },
  ),
  def('pig', 'Pig', 'animals', 1.2, 0.6, 0.8, 'pink', 'P0', ['farm'], 'wander'),
  def(
    'wolf',
    'Wolf',
    'animals',
    1.2,
    0.35,
    0.8,
    'pack of 3-5',
    'P1',
    ['forest'],
    'herd',
  ),
  def(
    'boar',
    'Boar',
    'animals',
    1.2,
    0.5,
    0.8,
    'tusks',
    'P1',
    ['forest'],
    'wander',
  ),
  def(
    'kangaroo',
    'Kangaroo',
    'animals',
    1.2,
    0.5,
    1.6,
    '',
    'P1',
    ['savanna'],
    'hop',
  ),
  def(
    'ostrich',
    'Ostrich',
    'animals',
    1.2,
    0.6,
    2.5,
    '',
    'P1',
    ['savanna'],
    'herd',
  ),
  def(
    'flower_patch',
    'Flower patch',
    'flora',
    1.2,
    1.2,
    0.3,
    'mixed flowers',
    'P0',
    ['meadow'],
    '-',
  ),
  def(
    'deer',
    'Deer',
    'animals',
    1.4,
    0.45,
    1.4,
    'antlers on variant 1',
    'P0',
    ['forest'],
    'herd',
    { variants: 2 },
  ),
  def(
    'alpaca',
    'Alpaca',
    'animals',
    1.4,
    0.5,
    1.7,
    'paint white / brown / grey',
    'P1',
    ['highlands'],
    'herd',
    { paints: WOOL2 },
  ),
  def(
    'antelope',
    'Antelope',
    'animals',
    1.4,
    0.4,
    1.3,
    '',
    'P1',
    ['savanna'],
    'herd',
  ),
  def(
    'panda',
    'Panda',
    'animals',
    1.4,
    0.8,
    1,
    'near the bamboo',
    'P1',
    ['jungle', 'zoo'],
    'wander',
  ),
  def(
    'warthog',
    'Warthog',
    'animals',
    1.3,
    0.5,
    0.8,
    '',
    'P2',
    ['savanna'],
    'wander',
  ),
  def(
    'boulder',
    'Boulder',
    'rocks',
    1.4,
    1.2,
    1,
    '',
    'P0',
    ['highlands', 'beach', 'savanna'],
    '-',
  ),
  def(
    'dirt_mound',
    'Dirt mound',
    'hills',
    1.4,
    1.4,
    0.5,
    'hill ladder',
    'P0',
    ['meadow', 'savanna'],
    '-',
    { variants: 3 },
  ),
  def('log', 'Log', 'flora', 1.4, 0.4, 0.4, '', 'P0', ['forest', 'bank'], '-'),
  def(
    'lab_desk',
    'Lab desk',
    'lab',
    1.4,
    0.7,
    1,
    'computer desk, glowing screen',
    'P1',
    ['lab'],
    '-',
  ),
  def(
    'termite_mound',
    'Termite mound',
    'hills',
    1.6,
    1.6,
    3.2,
    'tall stepped spire',
    'P0',
    ['savanna'],
    '-',
    { variants: 3 },
  ),
  def(
    'gorilla',
    'Gorilla',
    'animals',
    1.6,
    1,
    1.5,
    'knuckle walk; ladder: gorilla -> gorilla_big -> gorilla_giant',
    'P0',
    ['jungle', 'zoo'],
    'wander',
    { paints: FUR_DARK },
  ),
  def(
    'leopard',
    'Leopard',
    'animals',
    1.6,
    0.4,
    0.8,
    'spots',
    'P1',
    ['jungle'],
    'wander',
  ),
  def(
    'giraffe_calf',
    'Giraffe calf',
    'animals',
    1.6,
    0.5,
    3,
    'follows a giraffe',
    'P1',
    ['savanna'],
    'herd',
  ),
  def(
    'growth_vat',
    'Growth vat',
    'lab',
    1.6,
    1.6,
    3.2,
    'glass tank, green glow, a small animal inside (the lab signature)',
    'P0',
    ['lab'],
    '-',
  ),
  def(
    'bear',
    'Bear',
    'animals',
    1.9,
    0.9,
    1.3,
    'ladder: bear -> bear_giant',
    'P0',
    ['forest'],
    'wander',
  ),
  def(
    'tiger',
    'Tiger',
    'animals',
    1.9,
    0.6,
    1,
    'stripes',
    'P0',
    ['jungle'],
    'wander',
  ),
  def(
    'seal',
    'Seal',
    'animals',
    1.8,
    0.6,
    0.6,
    'flops (slow, bob)',
    'P1',
    ['beach'],
    'wander',
  ),
  def(
    'jungle_plant',
    'Jungle plant',
    'flora',
    1.8,
    1.8,
    1.6,
    'big leaves',
    'P0',
    ['jungle'],
    '-',
  ),
  def(
    'boulder_big',
    'Boulder big',
    'rocks',
    1.9,
    1.6,
    1.4,
    '',
    'P1',
    ['highlands'],
    '-',
  ),
  def(
    'zebra',
    'Zebra',
    'animals',
    2.2,
    0.6,
    1.4,
    'stripes',
    'P0',
    ['savanna'],
    'herd',
  ),
  def(
    'lion',
    'Lion',
    'animals',
    2.2,
    0.7,
    1.2,
    'mane on variant 1; ladder: lion -> lion_giant',
    'P0',
    ['savanna'],
    'wander',
    { variants: 2 },
  ),
  def(
    'frog_big',
    'Frog big',
    'animals',
    2.2,
    1.8,
    1.4,
    'lab stage 1, glowing collar',
    'P1',
    ['zoo', 'lab'],
    'hop',
  ),
  def(
    'ant_big',
    'Ant big',
    'animals',
    2.2,
    0.9,
    0.8,
    'lab stage 1, an escaped column near the lab',
    'P1',
    ['lab', 'meadow'],
    'trail',
  ),
  def(
    'fence_wood',
    'Fence wood',
    'zoo',
    2.1,
    0.1,
    1.2,
    'rows',
    'P0',
    ['farm', 'zoo'],
    '-',
  ),
  def(
    'zoo_fence',
    'Zoo fence',
    'zoo',
    5.5,
    0.1,
    2.5,
    'mesh panel, rows around the pens',
    'P0',
    ['zoo'],
    '-',
  ),
  def(
    'lab_fence',
    'Lab fence',
    'lab',
    8.5,
    0.15,
    3,
    'electric panel, glowing top wire',
    'P0',
    ['lab'],
    '-',
  ),
  def(
    'berry_bush',
    'Berry bush',
    'flora',
    2,
    2,
    1.3,
    'paint berries',
    'P1',
    ['forest'],
    '-',
    { paints: BERRY },
  ),
  def(
    'cow',
    'Cow',
    'animals',
    2.4,
    0.8,
    1.5,
    'patches (variants)',
    'P0',
    ['farm', 'meadow'],
    'herd',
    { variants: 3 },
  ),
  def(
    'horse',
    'Horse',
    'animals',
    2.4,
    0.7,
    1.7,
    'paint',
    'P1',
    ['farm', 'meadow'],
    'herd',
    { paints: HORSE },
  ),
  def(
    'camel',
    'Camel',
    'animals',
    2.6,
    0.8,
    2.2,
    '',
    'P1',
    ['savanna'],
    'wander',
  ),
  def(
    'elephant_calf',
    'Elephant calf',
    'animals',
    2.4,
    1.2,
    1.8,
    'follows the herd',
    'P0',
    ['savanna'],
    'herd',
  ),
  def(
    'hillock',
    'Hillock',
    'hills',
    2.5,
    2.5,
    0.8,
    '',
    'P0',
    ['meadow', 'highlands'],
    '-',
    { variants: 3 },
  ),
  def(
    'giraffe',
    'Giraffe',
    'animals',
    3,
    1.2,
    5.5,
    'tall, reads from far; ladder: giraffe_calf -> giraffe -> giraffe_giant',
    'P0',
    ['savanna'],
    'herd',
  ),
  def('moose', 'Moose', 'animals', 3, 1, 2.2, '', 'P1', ['forest'], 'wander'),
  def(
    'bison',
    'Bison',
    'animals',
    3,
    1.2,
    1.9,
    '',
    'P1',
    ['meadow', 'savanna'],
    'herd',
  ),
  def(
    'acacia',
    'Acacia',
    'flora',
    3,
    3,
    5,
    'flat crown',
    'P0',
    ['savanna'],
    '-',
  ),
  def(
    'boulder_pile',
    'Boulder pile',
    'rocks',
    3,
    2.6,
    1.6,
    '',
    'P1',
    ['highlands'],
    '-',
  ),
  def(
    'watchtower',
    'Watchtower',
    'lab',
    3,
    3,
    12,
    'searchlight (glow)',
    'P1',
    ['lab'],
    '-',
  ),
  def(
    'rabbit_big',
    'Rabbit big',
    'animals',
    3.5,
    1.8,
    3,
    'lab stage 1; one escaped near the start (first teeter target)',
    'P0',
    ['zoo', 'meadow'],
    'hop',
  ),
  def(
    'rhino',
    'Rhino',
    'animals',
    3.5,
    1.5,
    1.8,
    'ladder: rhino -> rhino_giant',
    'P0',
    ['savanna'],
    'wander',
  ),
  def(
    'research_jeep',
    'Research jeep',
    'labveh',
    3.5,
    1.8,
    1.8,
    'drives the compound loop road',
    'P0',
    ['lab', 'zoo'],
    'patrol',
    { paints: JEEP },
  ),
  def(
    'fallen_log',
    'Fallen log',
    'flora',
    3.4,
    0.8,
    0.8,
    '',
    'P1',
    ['forest', 'bank'],
    '-',
  ),
  def('keeper_hut', 'Keeper hut', 'zoo', 3.5, 3, 3, '', 'P1', ['zoo'], '-'),
  def(
    'feeding_station',
    'Feeding station',
    'zoo',
    3.2,
    3.2,
    2.5,
    '',
    'P1',
    ['zoo'],
    '-',
  ),
  def(
    'beetle_big',
    'Beetle big',
    'animals',
    4,
    2.6,
    1.8,
    'lab stage 1',
    'P1',
    ['lab', 'forest'],
    'skitter',
  ),
  def(
    'knoll',
    'Knoll',
    'hills',
    4,
    4,
    1.2,
    '',
    'P0',
    ['meadow', 'highlands'],
    '-',
    { variants: 3 },
  ),
  def('oak', 'Oak', 'flora', 4, 4, 8, '', 'P0', ['forest', 'meadow'], '-', {
    variants: 2,
  }),
  def(
    'cage_bars',
    'Cage bars',
    'zoo',
    8.5,
    0.5,
    9,
    'giant-cage bar section, rows around the giant pens',
    'P0',
    ['zoo'],
    '-',
  ),
  def(
    'lab_generator',
    'Lab generator',
    'lab',
    4,
    2,
    2.5,
    'glow',
    'P1',
    ['lab'],
    '-',
  ),
  def(
    'satellite_dish',
    'Satellite dish',
    'lab',
    4,
    4,
    5,
    '',
    'P1',
    ['lab'],
    '-',
  ),
  def(
    'crocodile',
    'Crocodile',
    'animals',
    4.5,
    1,
    0.7,
    'ladder: crocodile -> crocodile_big -> crocodile_giant',
    'P0',
    ['river', 'wetland'],
    'swim',
  ),
  def(
    'hippo',
    'Hippo',
    'animals',
    4.5,
    1.8,
    1.8,
    'half submerged while swimming; ladder: hippo -> hippo_giant',
    'P0',
    ['river', 'wetland'],
    'swim',
  ),
  def(
    'giant_carrot',
    'Giant carrot',
    'zoo',
    4.6,
    1.2,
    1.2,
    'food for the giant rabbits',
    'P1',
    ['zoo'],
    '-',
  ),
  def(
    'beaver_dam',
    'Beaver dam',
    'flora',
    4.8,
    2,
    1.5,
    'across a stream',
    'P1',
    ['river'],
    '-',
  ),
  def(
    'bamboo_grove',
    'Bamboo grove',
    'flora',
    4.5,
    4.5,
    7,
    '',
    'P1',
    ['jungle', 'zoo'],
    '-',
  ),
  def(
    'hill_5',
    'Hill 5',
    'hills',
    5.5,
    5.5,
    1.8,
    'terraced mound',
    'P0',
    ['highlands', 'everywhere'],
    '-',
    { variants: 3 },
  ),
  def(
    'jungle_tree',
    'Jungle tree',
    'flora',
    5.5,
    5.5,
    12,
    'buttress roots, tall',
    'P0',
    ['jungle'],
    '-',
  ),
  def(
    'gorilla_big',
    'Gorilla big',
    'animals',
    5,
    3,
    5,
    'lab stage 1',
    'P1',
    ['zoo'],
    'wander',
  ),
  def('zoo_shed', 'Zoo shed', 'zoo', 5.5, 5, 4, '', 'P1', ['zoo'], '-'),
  def(
    'elephant',
    'Elephant',
    'animals',
    6.4,
    2.2,
    3.4,
    'ladder: elephant_calf -> elephant -> elephant_big -> elephant_giant',
    'P0',
    ['savanna'],
    'herd',
  ),
  def(
    'tortoise_big',
    'Tortoise big',
    'animals',
    6,
    4.5,
    3,
    'lab stage 1',
    'P1',
    ['zoo', 'meadow'],
    'crawl',
  ),
  def(
    'container',
    'Container',
    'lab',
    6.1,
    2.4,
    2.6,
    'shipping container, paint',
    'P1',
    ['lab'],
    '-',
    { paints: BOX },
  ),
  def(
    'boulder_huge',
    'Boulder huge',
    'rocks',
    6,
    5,
    4,
    '',
    'P1',
    ['highlands'],
    '-',
  ),
  def(
    'growth_chamber',
    'Growth chamber',
    'lab',
    6,
    6,
    8,
    'big glowing tank with a bear inside',
    'P0',
    ['lab'],
    '-',
  ),
  def(
    'hill_7',
    'Hill 7',
    'hills',
    7,
    7,
    2.4,
    '',
    'P0',
    ['highlands', 'everywhere'],
    '-',
    { variants: 3 },
  ),
  def('baobab', 'Baobab', 'flora', 7, 7, 12, '', 'P0', ['savanna'], '-'),
  def(
    'transport_truck',
    'Transport truck',
    'labveh',
    7.5,
    2.5,
    3.5,
    'flatbed with a cage (big animal inside, part of the mesh)',
    'P0',
    ['lab', 'zoo'],
    'patrol',
  ),
  def(
    'greenhouse',
    'Greenhouse',
    'lab',
    7.5,
    5,
    4,
    'glass style',
    'P1',
    ['lab'],
    '-',
  ),
  def(
    'hill_9',
    'Hill 9',
    'hills',
    8.5,
    8.5,
    2.8,
    '',
    'P0',
    ['highlands', 'everywhere'],
    '-',
    { variants: 3 },
  ),
  def(
    'helicopter',
    'Helicopter',
    'labveh',
    8.5,
    2.5,
    3,
    'on the helipad',
    'P1',
    ['lab'],
    '-',
  ),
  def(
    'rock_arch',
    'Rock arch',
    'rocks',
    8.8,
    3,
    6,
    '',
    'P1',
    ['highlands', 'beach'],
    '-',
  ),
  def(
    'elephant_big',
    'Elephant big',
    'animals',
    8.8,
    3.5,
    5,
    'lab stage 1',
    'P1',
    ['zoo'],
    'wander',
  ),
  def(
    'log_bridge',
    'Log bridge',
    'flora',
    8.8,
    2.5,
    1.2,
    'plank bridge over the streams',
    'P0',
    ['river'],
    '-',
  ),
  def(
    'hill_10',
    'Hill 10',
    'hills',
    10,
    10,
    3.2,
    '',
    'P0',
    ['highlands'],
    '-',
    { variants: 3 },
  ),
  def('lab_dome', 'Lab dome', 'lab', 10, 10, 6, '', 'P0', ['lab'], '-'),
  def(
    'aviary',
    'Aviary',
    'zoo',
    10,
    10,
    9,
    'net dome with birds (part of the mesh)',
    'P1',
    ['zoo'],
    '-',
  ),
  def('barn', 'Barn', 'farm', 10, 8, 7, '', 'P1', ['farm'], '-'),
  def(
    'hill_12',
    'Hill 12',
    'hills',
    12,
    11,
    3.8,
    '',
    'P0',
    ['highlands'],
    '-',
    { variants: 3 },
  ),
  def(
    'lab_block',
    'Lab block',
    'lab',
    12,
    9,
    8,
    'punched windows',
    'P0',
    ['lab'],
    '-',
  ),
  def(
    'redwood',
    'Redwood',
    'flora',
    6,
    6,
    45,
    'very tall tree, height decides the tier',
    'P1',
    ['forest'],
    '-',
  ),
  def(
    'hill_14',
    'Hill 14',
    'hills',
    14,
    13,
    4.4,
    '',
    'P0',
    ['highlands'],
    '-',
    { variants: 3 },
  ),
  def(
    'lab_hangar',
    'Lab hangar',
    'lab',
    14,
    12,
    8,
    'big door half open, a giant crate inside',
    'P0',
    ['lab'],
    '-',
  ),
  def(
    'crocodile_big',
    'Crocodile big',
    'animals',
    13,
    3,
    2,
    'lab stage 1, escaped into the river',
    'P1',
    ['river'],
    'swim',
  ),
  def('hill_16', 'Hill 16', 'hills', 16, 15, 5, '', 'P0', ['highlands'], '-', {
    variants: 3,
  }),
  def(
    'rabbit_giant',
    'Rabbit giant',
    'giants',
    16,
    8,
    14,
    'GIANT',
    'P0',
    ['zoo', 'meadow'],
    'roam',
  ),
  def(
    'frog_giant',
    'Frog giant',
    'giants',
    15,
    13,
    9,
    'GIANT, sits in the big pond',
    'P0',
    ['zoo', 'wetland'],
    'roam',
  ),
  def(
    'mouse_giant',
    'Mouse giant',
    'giants',
    16,
    6,
    7,
    'GIANT, white lab mouse',
    'P1',
    ['lab', 'zoo'],
    'roam',
  ),
  def(
    'giraffe_giant',
    'Giraffe giant',
    'giants',
    15,
    6,
    64,
    'GIANT, the tallest thing on the island (visible from the start)',
    'P0',
    ['zoo', 'savanna'],
    'roam',
  ),
  def(
    'lab_tower',
    'Lab tower',
    'lab',
    14,
    14,
    60,
    'antenna mast, height decides the tier',
    'P1',
    ['lab'],
    '-',
  ),
  def('hill_19', 'Hill 19', 'hills', 19, 17, 6, '', 'P0', ['highlands'], '-', {
    variants: 3,
  }),
  def(
    'ant_giant',
    'Ant giant',
    'giants',
    18,
    8,
    6,
    'GIANT',
    'P0',
    ['lab', 'meadow'],
    'roam',
  ),
  def(
    'beetle_giant',
    'Beetle giant',
    'giants',
    19,
    12,
    8,
    'GIANT',
    'P1',
    ['zoo', 'forest'],
    'roam',
  ),
  def(
    'snail_giant',
    'Snail giant',
    'giants',
    18,
    8,
    12,
    'GIANT, slowest mover on the island',
    'P1',
    ['zoo', 'wetland'],
    'roam',
  ),
  def(
    'chicken_giant',
    'Chicken giant',
    'giants',
    18,
    10,
    18,
    'GIANT',
    'P1',
    ['zoo', 'farm'],
    'roam',
  ),
  def('lab_wing', 'Lab wing', 'lab', 19, 14, 10, '', 'P0', ['lab'], '-'),
  def('hill_22', 'Hill 22', 'hills', 22, 20, 7, '', 'P0', ['highlands'], '-', {
    variants: 3,
  }),
  def(
    'bear_giant',
    'Bear giant',
    'giants',
    22,
    11,
    15,
    'GIANT',
    'P0',
    ['zoo', 'forest'],
    'roam',
  ),
  def(
    'lion_giant',
    'Lion giant',
    'giants',
    22,
    7,
    12,
    'GIANT',
    'P1',
    ['zoo', 'savanna'],
    'roam',
  ),
  def(
    'biodome',
    'Biodome',
    'lab',
    22,
    22,
    14,
    'glass dome with jungle inside',
    'P0',
    ['lab'],
    '-',
  ),
  def('hill_26', 'Hill 26', 'hills', 26, 24, 8, '', 'P0', ['highlands'], '-', {
    variants: 3,
  }),
  def(
    'tortoise_giant',
    'Tortoise giant',
    'giants',
    26,
    20,
    13,
    'GIANT, trees on its shell (part of the mesh)',
    'P0',
    ['zoo', 'meadow'],
    'roam',
  ),
  def(
    'hippo_giant',
    'Hippo giant',
    'giants',
    25,
    10,
    10,
    'GIANT',
    'P1',
    ['zoo', 'river'],
    'roam',
  ),
  def(
    'rhino_giant',
    'Rhino giant',
    'giants',
    25,
    10,
    12,
    'GIANT',
    'P1',
    ['zoo', 'savanna'],
    'roam',
  ),
  def('hill_30', 'Hill 30', 'hills', 30, 27, 9, '', 'P1', ['highlands'], '-', {
    variants: 3,
  }),
  def(
    'crocodile_giant',
    'Crocodile giant',
    'giants',
    30,
    7,
    5,
    'GIANT, swims the main river',
    'P0',
    ['river', 'zoo'],
    'swim',
  ),
  def(
    'gorilla_giant',
    'Gorilla giant',
    'giants',
    28,
    20,
    36,
    'GIANT (generic giant ape, no film references)',
    'P0',
    ['zoo', 'jungle'],
    'roam',
  ),
  def(
    'growth_reactor',
    'Growth reactor',
    'lab',
    30,
    30,
    30,
    'ring machine aiming a growth ray at a pen (glow)',
    'P1',
    ['lab'],
    '-',
  ),
  def(
    'elephant_giant',
    'Elephant giant',
    'giants',
    34,
    14,
    22,
    'GIANT, the final boss of the island',
    'P0',
    ['zoo', 'savanna'],
    'roam',
  ),
  def(
    'lab_hq',
    'Lab hq',
    'lab',
    34,
    30,
    22,
    'the secret laboratory, 1 copy',
    'P0',
    ['lab'],
    '-',
  ),
  def(
    'hill_great',
    'Hill great',
    'hills',
    35,
    32,
    10,
    'highest hill, river source on top, 1 copy',
    'P1',
    ['highlands'],
    '-',
    { variants: 3 },
  ),
];
